/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BurgerButton: typeof import('./src/components/BurgerButton.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    copy: typeof import('./src/components/BurgerButton.vue')['default']
    PrimaryButton: typeof import('./src/components/PrimaryButton.vue')['default']
    PrimaryCard: typeof import('./src/components/PrimaryCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./src/components/ui/scroll-area/ScrollArea.vue')['default']
    ScrollBar: typeof import('./src/components/ui/scroll-area/ScrollBar.vue')['default']
    TheButton: typeof import('./src/components/ui/button/TheButton.vue')['default']
    TheCard: typeof import('./src/components/ui/card/TheCard.vue')['default']
    TheCardContent: typeof import('./src/components/ui/card/TheCardContent.vue')['default']
    TheCardDescription: typeof import('./src/components/ui/card/TheCardDescription.vue')['default']
    TheCardFooter: typeof import('./src/components/ui/card/TheCardFooter.vue')['default']
    TheCardHeader: typeof import('./src/components/ui/card/TheCardHeader.vue')['default']
    TheCardTitle: typeof import('./src/components/ui/card/TheCardTitle.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
