
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by @duplojs/to

export type parameters_0 = {
    query?: {
        name?: string | undefined;
        page?: number;
        withDisabled?: boolean | undefined;
    };
}

export type response_body_0_0 = {
    name: string;
    disabled: boolean;
    imageKey: string | null;
    imageUrl: string | null;
}[]

export type response_0_0 = {
    code: 200;
    ok: true;
    info: "categories";
} & {body: response_body_0_0};

export type parameters_1 = {
    query?: {
        address?: string | undefined;
    } | undefined;
}

export type response_body_1_0 = string[]

export type response_1_0 = {
    code: 200;
    ok: true;
    info?: undefined;
} & {body: response_body_1_0};

export type parameters_2 = {
    params: {
        categoryName: string;
    };
    query?: {
        page?: number;
    } | undefined;
}

export type response_2_0 = {
    code: 404;
    ok: false;
    info: "category.notfound";
} & {body: undefined};

export type response_body_2_1 = {
    id: string;
    name: string;
    description: string;
    shortDescription: string;
    price: number;
    createdAt?: string;
    updatedAt?: string;
    organizationId: string;
}[]

export type response_2_1 = {
    code: 200;
    ok: true;
    info: "category.products";
} & {body: response_body_2_1};

export type response_body_3_0 = ({
    type: "PARENT_CATEGORY";
    parentCategoryName: string;
    categories: {
        categoryName: string;
        categoryImageUrl: string;
    }[];
} | {
    type: "CATEGORY";
    categoryName: string;
} | {
    type: "LINK";
    title: string;
    url: string;
})[]

export type response_3_0 = {
    code: 200;
    ok: true;
    info: "navigationBar";
} & {body: response_body_3_0};

export type response_4_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_4_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_4_2 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_5_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_5_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_5_2 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type parameters_6 = {
    params: {
        organizationId: string;
    };
}

export type response_6_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_6_1 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_6_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_6_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type parameters_7 = {
    params: {
        organizationId: string;
        warehouseId?: string | undefined;
    };
}

export type response_7_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_7_1 = {
    code: 401;
    ok: false;
    info: "entry.refuse";
} & {body: undefined};

export type response_7_2 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_7_3 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_7_4 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type parameters_8 = {
    params: {
        organizationId: string;
        productSheetId?: string | undefined;
    };
}

export type response_8_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_8_1 = {
    code: 401;
    ok: false;
    info: "entry.refuse";
} & {body: undefined};

export type response_8_2 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_8_3 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_8_4 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type parameters_9 = {
    params: {
        organizationId: string;
    };
}

export type response_9_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_9_1 = {
    code: 401;
    ok: false;
    info: "entry.refuse";
} & {body: undefined};

export type response_9_2 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_10_0 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_11_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_11_1 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_12_0 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type request_body_13 = {
    name: string;
    disabled: boolean;
}

export type response_13_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_13_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_13_2 = {
    code: 409;
    ok: false;
    info: "category.alreadyExist";
} & {body: undefined};

export type response_body_13_3 = {
    name: string;
    disabled: boolean;
    imageKey: string | null;
    imageUrl: string | null;
}

export type response_13_3 = {
    code: 201;
    ok: true;
    info: "category.created";
} & {body: response_body_13_3};

export type request_body_14 = {
    name?: string | undefined;
    disabled?: boolean | undefined;
} | undefined

export type parameters_14 = {
    params: {
        categoryName: string;
    };
}

export type response_14_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_14_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_14_2 = {
    code: 404;
    ok: false;
    info: "category.notfound";
} & {body: undefined};

export type response_14_3 = {
    code: 409;
    ok: false;
    info: "category.alreadyExist";
} & {body: undefined};

export type response_14_4 = {
    code: 204;
    ok: true;
    info: "category.edited";
} & {body: undefined};

export type request_body_11 = {
    organizationRole?: ("STORE_KEEPER" | "PRODUCT_SHEET_MANAGER" | "ACCOUNTANT") | undefined;
}

export type parameters_11 = {
    params: {
        organizationId: string;
    };
}

export type response_11_0 = {
    code: 401;
    ok: false;
    info: "firebase.token.invalid";
} & {body: undefined};

export type response_11_1 = {
    code: 406;
    ok: false;
    info: "user.address.invalid";
} & {body: undefined};

export type response_11_2 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_11_3 = {
    code: 204;
    ok: true;
    info: "organization.user";
} & {body: response_body_16_2};

export type response_11_4 = {
    code: 406;
    ok: false;
    info: "category.image.missing";
} & {body: undefined};

export type response_11_5 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type parameters_12 = {
    params: {
        organizationId: string;
    };
}

export type response_12_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_12_1 = {
    code: 406;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_12_2 = {
    code: 401;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_12_3 = {
    code: 204;
    ok: true;
    info: "organization.user.deleted";
} & {body: undefined};

export type response_12_4 = {
    code: 406;
    ok: false;
    info: "user.notfound";
} & {body: undefined};

export type response_12_5 = {
    code: 403;
    ok: false;
    info: "organization.hasAlreadyUser";
} & {body: undefined};

export type response_17_2 = {
    code: 200;
    ok: true;
    info: "navigationItems";
} & {body: response_body_17_2};

export type request_body_18 = {
    id: string;
    priority: number;
    type: "PARENT_CATEGORY";
    parentCategoryName: string;
} | {
    id: string;
    priority: number;
    type: "CATEGORY";
    categoryName: string;
} | {
    id: string;
    priority: number;
    type: "LINK";
    url: string;
    title: string;
}

export type request_body_13 = string

export type response_13_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_13_1 = {
    code: 404;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_body_13_2 = string

export type response_13_2 = {
    code: 200;
    ok: true;
    info: "user.logged";
} & {body: response_body_13_2};

export type request_body_14 = {
    fireBaseIdToken: string;
    lastname: string;
    firstname: string;
    address: string;
    dateOfBirth: Date;
}

export type response_14_0 = {
    code: 401;
    ok: false;
    info: "firebase.token.invalid";
} & {body: undefined};

export type response_14_1 = {
    code: 409;
    ok: false;
    info: "user.alreadyExist";
} & {body: undefined};

export type response_14_2 = {
    code: 400;
    ok: false;
    info: "parentCategory.notfound";
} & {body: undefined};

export type response_14_3 = {
    code: 400;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_14_4 = string

export type response_14_4 = {
    code: 201;
    ok: true;
    info: "user.registered";
} & {body: response_body_14_4};

export type response_15_0 = {
    code: 401;
    ok: false;
    info: "user.notfound";
} & {body: undefined};

export type response_15_1 = {
    code: 404;
    ok: false;
    info: "organization.hasAlreadyUser";
} & {body: undefined};

export type response_body_15_2 = {
    id: string;
    name: string;
    description: string;
    shortDescription: string;
    price: number;
    createdAt?: string;
    updatedAt?: string;
    organizationId: string;
}

export type response_15_2 = {
    code: 200;
    ok: true;
    info: "user";
} & {body: response_body_15_2};

export type parameters_16 = {
    params: {
        imageProductSheetId: string;
    };
}

export type response_16_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_16_1 = {
    code: 404;
    ok: false;
    info: "organization.hasNotUser";
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_16_2 = {
    code: 204;
    ok: true;
    info: "imageProductSheet.deleted";
} & {body: undefined};

export type response_16_3 = {
    code: 406;
    ok: false;
    info: "category.alreadyExist";
} & {body: undefined};

export type response_16_4 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type parameters_17 = {
    params: {
        organizationId: string;
        organizationId: string;
    };
}

export type response_17_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_17_1 = {
    code: 406;
    ok: false;
    info: "parentCategory.notfound";
} & {body: undefined};

export type response_body_17_2 = {
    id: string;
    email: string;
    lastname: string;
    firstname: string;
    dateOfBirth?: string;
    address: string;
    primordialRole: "CUSTOMER" | "MODERATOR" | "CONTENTS_MASTER" | "ADMIN";
    muted: boolean;
}

export type response_17_2 = {
    code: 200;
    ok: true;
    info: "organization.user";
} & {body: response_body_17_2};

export type request_body_18 = {
    email: string;
    firstname: string;
    lastname: string;
    organizationRole: "STORE_KEEPER" | "PRODUCT_SHEET_MANAGER" | "ACCOUNTANT";
}

export type parameters_18 = {
    params: {
        organizationId: string;
        organizationId: string;
    };
}

export type response_18_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_18_1 = {
    code: 404;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_18_2 = {
    code: 406;
    ok: false;
    info: "parentCategory.notfound";
} & {body: undefined};

export type response_body_22_4 = {
    id: string;
    name: string;
    disabled: boolean;
    imageKey: string | null;
    imageUrl: string | null;
}

export type response_18_3 = {
    code: 403;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_18_4 = {
    code: 404;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_18_5 = {
    code: 409;
    ok: false;
    info: "organization.hasAlreadyUser";
} & {body: undefined};

export type response_18_6 = {
    code: 201;
    ok: true;
    info: "organization.user.add";
} & {body: undefined};

export type request_body_19 = {
    name: string;
    disabled: boolean;
}

export type response_19_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_19_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_19_2 = {
    code: 409;
    ok: false;
    info: "navigationItem.limit";
} & {body: undefined};

export type response_19_3 = {
    code: 201;
    ok: true;
    info: "users";
} & {body: response_body_25_2};

export type request_body_26 = {
    name: string;
}

export type response_26_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type request_body_20 = {
    name?: string | undefined;
    disabled?: boolean | undefined;
} | undefined

export type parameters_20 = {
    params: {
        categoryName: string;
    };
}

export type response_20_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_20_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_20_2 = {
    code: 404;
    ok: false;
    info: "category.notfound";
} & {body: undefined};

export type response_20_3 = {
    code: 409;
    ok: false;
    info: "parentCategory.notfound";
} & {body: undefined};

export type response_20_4 = {
    code: 204;
    ok: true;
    info: "navigationItem.edited";
} & {body: undefined};

export type request_body_21 = {
    suspended?: boolean | undefined;
}

export type parameters_21 = {
    params: {
        organizationId: string;
        userId: string;
    };
}

export type response_21_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_21_1 = {
    code: 403;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_21_2 = {
    code: 404;
    ok: false;
    info: "organization.user.organizationRole.owner";
} & {body: undefined};

export type response_21_3 = {
    code: 204;
    ok: true;
    info: "organization.user.edited";
} & {body: undefined};

export type response_28_4 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_28_5 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type parameters_22 = {
    query?: {
        page?: number;
        name?: string | undefined;
    } | undefined;
}

export type response_22_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_22_1 = {
    code: 403;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_body_22_2 = {
    id: string;
    name: string;
    label: string | null;
    ownerId: string;
    suspended: boolean;
}[]

export type response_22_2 = {
    code: 200;
    ok: true;
    info: "organizations";
} & {body: response_body_22_2};

export type request_body_30 = {
    suspended?: boolean | undefined;
}

export type parameters_30 = {
    params: {
        organizationId: string;
    };
}

export type response_30_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_30_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_30_2 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_30_3 = {
    code: 204;
    ok: true;
    info: "organization.edited";
} & {body: undefined};

export type request_body_24 = {
    primordialRole?: ("CUSTOMER" | "CONTENTS_MASTER" | "MODERATOR") | undefined;
    muted?: boolean | undefined;
}

export type parameters_32 = {
    params: {
        userId: string;
    };
}

export type response_32_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_24_1 = {
    code: 403;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_24_2 = {
    code: 404;
    ok: false;
    info: "user.notfound";
} & {body: undefined};

export type response_24_3 = {
    code: 401;
    ok: false;
    info: "user.primordialRole.admin";
} & {body: undefined};

export type response_body_24_4 = {
    id: string;
    name: string;
    disabled: boolean;
}[]

export type response_24_4 = {
    code: 204;
    ok: true;
    info: "user.edited";
} & {body: undefined};

export type request_body_33 = {
    suspended?: boolean | undefined;
}

export type parameters_25 = {
    query?: {
        page?: number;
        email?: string | undefined;
        primordialRole?: (("CUSTOMER" | "MODERATOR" | "CONTENTS_MASTER" | "ADMIN") | ("CUSTOMER" | "MODERATOR" | "CONTENTS_MASTER" | "ADMIN")[]) | undefined;
    } | undefined;
}

export type response_33_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_25_1 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_25_2 = {
    id: string;
    email: string;
    lastname: string;
    firstname: string;
    dateOfBirth?: string;
    address: string;
    primordialRole: "CUSTOMER" | "MODERATOR" | "CONTENTS_MASTER" | "ADMIN";
    muted: boolean;
}[]

export type response_25_2 = {
    code: 200;
    ok: true;
    info: "users";
} & {body: response_body_25_2};

export type parameters_26 = {
    params: {
        organizationId: string;
    };
    query?: {
        page?: number;
        name?: string | undefined;
    } | undefined;
}

export type response_35_0 = {
    code: 401;
    ok: false;
    info: "firebase.token.invalid";
} & {body: undefined};

export type response_35_1 = {
    code: 409;
    ok: false;
    info: "user.alreadyExist";
} & {body: undefined};

export type response_35_2 = {
    code: 400;
    ok: false;
    info: "user.address.invalid";
} & {body: undefined};

export type response_35_3 = {
    code: 400;
    ok: false;
    info: "user.dateOfBirth.invalid";
} & {body: undefined};

export type response_body_35_4 = string

export type response_35_4 = {
    code: 201;
    ok: true;
    info: "user.registered";
} & {body: response_body_35_4};

export type request_body_36 = {
    primordialRole?: ("CUSTOMER" | "CONTENTS_MASTER" | "MODERATOR") | undefined;
    muted?: boolean | undefined;
}

export type parameters_36 = {
    params: {
        userId: string;
    };
}

export type response_36_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_36_1 = {
    code: 403;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_36_2 = {
    code: 404;
    ok: false;
    info: "parentCategory.notfound";
} & {body: undefined};

export type response_36_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_26_4 = {
    id: string;
    name: string;
    description: string;
    shortDescription: string;
    price: number;
    createdAt?: string;
    updatedAt?: string;
    organizationId: string;
}[]

export type response_26_4 = {
    code: 200;
    ok: true;
    info: "productSheets.found";
} & {body: response_body_26_4};

export type request_body_27 = {
    name: string;
    description: string;
    shortDescription: string;
    price: number;
}

export type parameters_37 = {
    params: {
        productSheetId: string;
    };
    query?: {
        page?: number;
        name?: string | undefined;
    } | undefined;
}

export type response_37_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_37_1 = {
    code: 404;
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_37_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_37_3 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_27_4 = {
    code: 201;
    ok: true;
    info: "productSheet.created";
} & {body: response_body_27_4};

export type parameters_38 = {
    params: {
        productSheetId: string;
    };
    query?: {
        page?: number;
        name?: string | undefined;
    } | undefined;
}

export type response_38_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_38_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_38_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_38_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_28_4 = {
    id: string;
    email: string;
    lastname: string;
    firstname: string;
    organizationRole: "STORE_KEEPER" | "PRODUCT_SHEET_MANAGER" | "ACCOUNTANT" | "OWNER";
}[]

export type response_28_4 = {
    code: 200;
    ok: true;
    info: "organization.users";
} & {body: response_body_28_4};

export type request_body_29 = {
    name: string;
    address: string;
}

export type parameters_39 = {
    params: {
        productSheetId: string;
    };
}

export type response_39_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_39_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_39_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_39_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_29_4 = {
    code: 400;
    ok: false;
    info: "warehouse.address.invalid";
} & {body: undefined};

export type response_body_29_5 = {
    id: string;
    productSheetId: string;
    organizationId: string;
}

export type response_29_5 = {
    code: 201;
    ok: true;
    info: "warehouse.created";
} & {body: response_body_29_5};

export type request_body_30 = {
    name?: string | undefined;
    address?: string | undefined;
}

export type parameters_30 = {
    params: {
        warehouseId: string;
    };
}

export type response_40_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_40_1 = {
    code: 404;
    ok: false;
    info: "warehouse.notfound";
} & {body: undefined};

export type response_40_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_40_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_40_4 = {
    code: 204;
    ok: true;
    info: "organization.edited";
} & {body: undefined};

export type parameters_41 = {
    headers: {
        "content-type": string;
        "content-length": number;
    };
    params: {
        organizationId: string;
    };
}

export type response_41_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_41_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_30_4 = {
    code: 400;
    ok: false;
    info: "product.images.limit";
} & {body: undefined};

export type response_30_5 = {
    code: 204;
    ok: true;
    info: "warehouse.edited";
} & {body: undefined};

export type parameters_42 = {
    params: {
        organizationId: string;
        organizationId: string;
    };
}

export type response_42_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_31_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_31_2 = {
    code: 406;
    ok: false;
    info: "user.notfound";
} & {body: undefined};

export type response_31_3 = {
    code: 403;
    ok: false;
    info: "user.primordialRole.admin";
} & {body: undefined};

export type response_body_31_4 = {
    id: string;
    name: string;
    address: string;
    organizationId: string;
}[]

export type response_31_4 = {
    code: 200;
    ok: true;
    info: "warehouses.found";
} & {body: response_body_31_4};

export type request_body_32 = {
    categoryId: string;
}

export type parameters_45 = {
    params: {
        organizationId: string;
    };
    query?: {
        page?: number;
        name?: string | undefined;
    } | undefined;
}

export type response_45_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_45_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_45_2 = {
    code: 406;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_45_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_45_4 = {
    id: string;
    email: string;
    lastname: string;
    firstname: string;
    organizationRole: "STORE_KEEPER" | "PRODUCT_SHEET_MANAGER" | "ACCOUNTANT" | "OWNER";
}[]

export type response_45_4 = {
    code: 200;
    ok: true;
    info: "organization.users";
} & {body: response_body_45_4};

export type parameters_46 = {
    params: {
        organizationId: string;
    };
    query?: {
        page?: number;
        name?: string | undefined;
    } | undefined;
}

export type response_46_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_46_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_46_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_46_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_32_4 = {
    code: 404;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_32_5 = {
    code: 409;
    ok: false;
    info: "product.categories.limit";
} & {body: undefined};

export type response_32_6 = {
    code: 200;
    ok: true;
    info: "productSheet.created";
} & {body: response_body_32_4};

export type parameters_48 = {
    params: {
        organizationId: string;
    };
    query?: {
        page?: number;
        name?: string | undefined;
    } | undefined;
}

export type response_48_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_48_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_48_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_48_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_33_4 = {
    id: string;
    name: string;
    disabled: boolean;
}[]

export type response_48_4 = {
    code: 200;
    ok: true;
    info: "productSheet.categories";
} & {body: response_body_33_4};

export type parameters_49 = {
    params: {
        productSheetId: string;
        categoryId: string;
    };
    query?: {
        page?: number;
        email?: string | undefined;
    } | undefined;
}

export type response_49_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_49_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_49_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_49_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_34_4 = {
    code: 404;
    ok: false;
    info: "category.notfound";
} & {body: undefined};

export type response_34_5 = {
    code: 200;
    ok: true;
    info: "productSheet.category.untied";
} & {body: undefined};

export type parameters_50 = {
    params: {
        organizationId: string;
    };
    query?: {
        page?: number;
        name?: string | undefined;
    } | undefined;
}

export type response_50_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_50_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_50_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_50_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_35_4 = {
    id: string;
    name: string;
    description: string;
    shortDescription: string;
    price: number;
    createdAt?: string;
    updatedAt?: string;
    name: string;
    description: string;
    shortDescription: string;
    price: number;
    createdAt?: string;
    updatedAt?: string;
    organizationId: string;
}

export type response_50_4 = {
    code: 200;
    ok: true;
    info: "productSheet.found";
} & {body: response_body_35_4};

export type request_body_36 = {
    name?: string | undefined;
    description?: string | undefined;
    shortDescription?: string | undefined;
    price?: number | undefined;
}

export type parameters_36 = {
    params: {
        organizationId: string;
    };
}

export type response_51_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_51_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_51_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_51_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_51_4 = string

export type response_body_36_4 = string

export type response_36_4 = {
    code: 201;
    ok: true;
    info: "productSheet.edited";
} & {body: response_body_36_4};

export type parameters_37 = {
    params: {
        productSheetId: string;
    };
}

export type response_52_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_37_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_37_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_37_3 = {
    code: 403;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_body_37_4 = {
    id: string;
    name: string;
    description: string;
    shortDescription: string;
    price: number;
    createdAt?: string;
    updatedAt?: string;
    organizationId: string;
}

export type response_37_4 = {
    code: 200;
    ok: true;
    info: "productSheet.images";
} & {body: response_body_37_4};

export type parameters_38 = {
    headers: {
        "content-type": string;
        "content-length": number;
    };
    params: {
        warehouseId: string;
    };
}

export type response_55_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_55_1 = {
    code: 404;
    ok: false;
    info: "warehouse.notfound";
} & {body: undefined};

export type response_55_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_55_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_38_4 = {
    code: 409;
    ok: false;
    info: "product.images.limit";
} & {body: undefined};

export type response_38_5 = {
    code: 400;
    ok: false;
    info: "productSheet.image.missing";
} & {body: undefined};

export type response_body_38_6 = {
    id: string;
    productSheetId: string;
    organizationId: string;
    url: string;
    key: string;
    alt: string | null;
}

export type response_38_6 = {
    code: 201;
    ok: true;
    info: "productSheet.image.create";
} & {body: response_body_38_6};

export type GetDef<
	method extends DefEnrichedDuplojsTo["method"],
	path extends Extract<
		DefEnrichedDuplojsTo, 
		{method: method}
	>["path"] = any, 
> = Extract<
	DefEnrichedDuplojsTo, 
	{
		method: method,
		path: path
	}
>;

export type DefDefinition = {
	path: string,
	method: string,
	body: unknown,
	parameters: unknown,
	response: ResponseDefinition,
}

export type GetResponseByInfo<
	def extends DefDefinition,
	info extends def["response"]["info"]
> = Extract<
	def["response"], 
	{
		info: info
	}
>;

export type GetResponseByCode<
	def extends DefDefinition,
	code extends def["response"]["code"]
> = Extract<
	def["response"], 
	{
		code: code
	}
>;

export type DefEnrichedDuplojsTo = {
	path: "/categories",
	method: "GET",
	body: unknown,
	parameters: parameters_0,
	response: response_0_0,
} | {
	path: "/geocoder",
	method: "GET",
	body: unknown,
	parameters: parameters_1,
	response: response_1_0,
} | {
	path: "/category/{categoryName}/product-sheets",
	method: "GET",
	body: unknown,
	parameters: parameters_2,
	response: response_2_0
		| response_2_1,
} | {
	path: "/navigation-bar",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_3_0,
} | {
	path: "/entry/admin-panel*",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_4_0
		| response_4_1
		| response_4_2,
} | {
	path: "/entry/content-panel*",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_5_0
		| response_5_1
		| response_5_2,
} | {
	path: "/entry/organization/{organizationId}/manage-user" | "/entry/organization/{organizationId}/manage",
	method: "GET",
	body: unknown,
	parameters: parameters_6,
	response: response_6_0
		| response_6_1
		| response_6_2
		| response_6_3,
} | {
	path: "/entry/organization/{organizationId}/warehouses" | "/entry/organization/{organizationId}/create-warehouse" | "/entry/organization/{organizationId}/edited-warehouse/{warehouseId}",
	method: "GET",
	body: unknown,
	parameters: parameters_7,
	response: response_7_0
		| response_7_1
		| response_7_2
		| response_7_3
		| response_7_4,
} | {
	path: "/entry/organization/{organizationId}/product-sheets" | "/entry/organization/{organizationId}/edit-product-sheet/{productSheetId}" | "/entry/organization/{organizationId}/create-product-sheet",
	method: "GET",
	body: unknown,
	parameters: parameters_8,
	response: response_8_0
		| response_8_1
		| response_8_2
		| response_8_3
		| response_8_4,
} | {
	path: "/entry/organization/{organizationId}*",
	method: "GET",
	body: unknown,
	parameters: parameters_9,
	response: response_9_0
		| response_9_1
		| response_9_2,
} | {
	path: "/entry/login" | "/entry/register",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_10_0,
} | {
	path: "/entry/edit-profile",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_11_0
		| response_11_1,
} | {
	path: "/entry*",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_11_0,
} | {
	path: "/organization/{organizationId}/user/{userId}",
	method: "PATCH",
	body: request_body_11,
	parameters: parameters_11,
	response: response_11_0
		| response_11_1
		| response_11_2
		| response_11_3
		| response_11_4
		| response_11_5,
} | {
	path: "/organization/{organizationId}/user/{userId}",
	method: "DELETE",
	body: unknown,
	parameters: parameters_12,
	response: response_12_0
		| response_12_1
		| response_12_2
		| response_12_3
		| response_12_4
		| response_12_5,
} | {
	path: "/category",
	method: "POST",
	body: request_body_13,
	parameters: parameters_13,
	response: response_13_0
		| response_13_1
		| response_13_2,
		| response_13_2,
} | {
	path: "/register",
	method: "POST",
	body: request_body_14,
	path: "/register",
	method: "POST",
	body: request_body_14,
	parameters: parameters_14,
	response: response_14_0
		| response_14_1
		| response_14_2
		| response_14_3
		| response_14_4,
		| response_14_2
		| response_14_3
		| response_14_4,
} | {
	path: "/user",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_15_0
		| response_15_1
		| response_15_2
		| response_15_3
		| response_15_4,
} | {
	path: "/organization/{organizationId}/user",
	method: "POST",
	body: request_body_16,
	parameters: parameters_16,
	response: response_16_0
		| response_16_1
		| response_16_2
		| response_16_3
		| response_16_4
		| response_16_5
		| response_16_6,
} | {
	path: "/organization/{organizationId}/user",
	method: "GET",
	body: unknown,
	parameters: parameters_17,
	response: response_17_0
		| response_17_1
		| response_17_2,
		| response_17_2,
} | {
	path: "/organization/{organizationId}/user",
	method: "POST",
	body: request_body_18,
	parameters: parameters_18,
	response: response_18_0
		| response_18_1
		| response_18_2
		| response_18_3
		| response_18_4
		| response_18_5
		| response_18_6,
} | {
	path: "/category",
	method: "POST",
	body: request_body_19,
	parameters: undefined,
	response: response_19_0
		| response_19_1
		| response_19_2
		| response_19_3,
} | {
	path: "/parent-category/{parentCategoryName}",
	method: "PATCH",
	body: request_body_20,
	parameters: parameters_20,
	response: response_20_0
		| response_20_1
		| response_20_2
		| response_20_3
		| response_20_4,
} | {
	path: "/organization/{organizationId}@admin",
	method: "PATCH",
	body: request_body_21,
	parameters: undefined,
	response: response_21_0
		| response_21_1
		| response_21_2
		| response_21_3,
} | {
	path: "/organizations",
	method: "GET",
	body: unknown,
	parameters: parameters_22,
	response: response_22_0
		| response_22_1
		| response_22_2,
} | {
	path: "/parent-category/{parentCategoryName}/category/{categoryName}",
	method: "DELETE",
	body: unknown,
	parameters: parameters_23,
	response: response_23_0
		| response_23_1
		| response_23_2
		| response_23_3,
} | {
	path: "/user/{userId}@admin",
	method: "PATCH",
	body: request_body_24,
	parameters: parameters_24,
	response: response_24_0
		| response_24_1
		| response_24_2,
} | {
	path: "/users",
	method: "GET",
	body: unknown,
	parameters: parameters_25,
	path: "/users",
	method: "GET",
	body: unknown,
	parameters: parameters_25,
	response: response_25_0
		| response_25_1
		| response_25_2,
		| response_25_2,
} | {
	path: "/organization/{organizationId}/product-sheets",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_26_0
		| response_26_1
		| response_26_2
		| response_26_3
		| response_26_4,
} | {
	path: "/organization/{organizationId}/product-sheet",
	method: "POST",
	body: request_body_27,
	parameters: parameters_27,
	response: response_27_0
		| response_27_1
		| response_27_2,
} | {
	path: "/organization/{organizationId}/users",
	method: "GET",
	body: unknown,
	parameters: parameters_28,
	response: response_28_0
		| response_28_1
		| response_28_2
		| response_28_3
		| response_28_4
		| response_28_5,
} | {
	path: "/organization/{organizationId}/warehouse",
	method: "POST",
	body: request_body_29,
	parameters: parameters_29,
	response: response_29_0
		| response_29_1
		| response_29_2
		| response_29_3
		| response_29_4
		| response_29_5,
		| response_29_3
		| response_29_4
		| response_29_5,
} | {
	path: "/warehouse/{warehouseId}",
	method: "PATCH",
	body: request_body_30,
	parameters: parameters_30,
	response: response_30_0
		| response_30_1
		| response_30_2
		| response_30_3
		| response_30_4
		| response_30_5
		| response_30_6,
} | {
	path: "/organization/{organizationId}/warehouses",
	method: "GET",
	body: unknown,
	parameters: parameters_31,
	response: response_31_0
		| response_31_1
		| response_31_2
		| response_31_3
		| response_31_4
		| response_31_5,
} | {
	path: "/product-sheet/{productSheetId}/category",
	method: "POST",
	body: request_body_32,
	parameters: parameters_32,
	response: response_32_0
		| response_32_1
		| response_32_2,
} | {
	path: "/product-sheet/{productSheetId}/categories",
	method: "GET",
	body: unknown,
	parameters: parameters_33,
	response: response_33_0
		| response_33_1
		| response_33_2
		| response_33_3
		| response_33_4
		| response_33_5
		| response_33_6,
} | {
	path: "/product-sheet/{productSheetId}/category/{categoryId}",
	method: "DELETE",
	body: unknown,
	parameters: parameters_34,
	response: response_34_0
		| response_34_1
		| response_34_2
		| response_34_3
		| response_34_4
		| response_34_5,
} | {
	path: "/product-sheet/{productSheetId}",
	method: "GET",
	body: unknown,
	parameters: parameters_35,
	response: response_35_0
		| response_35_1
		| response_35_2
		| response_35_3
		| response_35_4,
} | {
	path: "/product-sheet/{productSheetId}",
	method: "PATCH",
	body: request_body_36,
	parameters: parameters_36,
	response: response_36_0
		| response_36_1
		| response_36_2
		| response_36_3
		| response_36_4
		| response_36_5,
} | {
	path: "/product-sheet/{productSheetId}/images",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_37_0
		| response_37_1
		| response_37_2,
		| response_37_2,
} | {
	path: "/product-sheet/{productSheetId}/image",
	method: "POST",
	body: unknown,
	parameters: parameters_38,
	response: response_38_0
		| response_38_1
		| response_38_2
		| response_38_3
		| response_38_4
		| response_38_5
		| response_38_6,
};


export type BaseRequestParameters = {
	disabledPrefix?: boolean,
} & Omit<RequestInit, "headers" | "method">;

export type UndefinedRequestParameters = {
	headers?: string | string[];
}

export type DefToArgumentsWithInfo<
	responseDefinition extends ResponseDefinition
> = responseDefinition extends ResponseDefinition 
	? [data: responseDefinition["body"], info: responseDefinition["info"]]
	: never

export type DefToArgumentsWithCode<
	responseDefinition extends ResponseDefinition
> = responseDefinition extends ResponseDefinition 
	? [data: responseDefinition["body"], code: responseDefinition["code"]]
	: never

export type RequestCallbackError = (error: Error) => void

export type ResponseObjectError = {
	success: false,
	error: Error,
}

export interface ResponseDefinition {
	code: number;
	ok: boolean;
	info?: string;
	body?: any;
}

export type RepDefToResponseObject<repDef extends ResponseDefinition> = 
	repDef extends ResponseDefinition 
		? {
			success: true,
			response: Response,
			data: repDef["body"],
			info: repDef["info"],
			code: repDef["code"]
		}
		: never

export declare class EnrichedRequestor<
	repDef extends ResponseDefinition
>{

	s(cb: (data: Extract<repDef, {ok: true}>["body"]) => void): this;
	sd(): Promise<
		Extract<repDef, {ok: true}>["body"]
	>;

	e(cb: (data: Extract<repDef, {ok: false}>["body"]) => void): this;
	ed(): Promise<
		Extract<repDef, {ok: false}>["body"]
	>;

	info<_info extends repDef["info"]>(
		info: _info | _info[],
		cb: (...args: DefToArgumentsWithInfo<Extract<repDef, {info: _info}>>) => void
	): this;
	id<_info extends repDef["info"]>(info: _info | _info[]): Promise<
		Extract<repDef, {info: _info}>["body"]
	>;

	code<_code extends repDef["code"]>(
		code: _code | _code[],
		cb: (...args: DefToArgumentsWithCode<Extract<repDef, {code: _code}>>) => void
	): this;
	cd<_code extends repDef["code"]>(code: _code | _code[]): Promise<
		Extract<repDef, {code: _code}>["body"]
	>;

	then(cb: (response: RepDefToResponseObject<repDef>) => void): this;
	catch(cb: RequestCallbackError): this;
	finally(cb: (response: RepDefToResponseObject<repDef> | ResponseObjectError) => void): this;
	result: Promise<
		| RepDefToResponseObject<repDef>
		| ResponseObjectError
	>;
}

export interface EnrichedDuploTo<
	interceptorParameter extends {} = {},
>{
	
	get(
		path: "/categories", 
		parameters ?: parameters_0 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_0_0
	>

	get(
		path: "/geocoder", 
		parameters ?: parameters_1 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_1_0
	>

	get(
		path: "/category/{categoryName}/product-sheets", 
		parameters : parameters_2 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_2_0
		| response_2_1
	>

	get(
		path: "/navigation-bar", 
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_3_0
	>

	get(
		path: "/entry/admin-panel*", 
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_4_0
		| response_4_1
		| response_4_2
	>

	get(
		path: "/entry/content-panel*", 
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_5_0
		| response_5_1
		| response_5_2
	>

	get(
		path: "/entry/organization/{organizationId}/manage-user" | "/entry/organization/{organizationId}/manage", 
		parameters : parameters_6 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_6_0
		| response_6_1
		| response_6_2
		| response_6_3
	>

	get(
		path: "/entry/organization/{organizationId}/warehouses" | "/entry/organization/{organizationId}/create-warehouse" | "/entry/organization/{organizationId}/edited-warehouse/{warehouseId}", 
		parameters : parameters_7 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_7_0
		| response_7_1
		| response_7_2
		| response_7_3
		| response_7_4
	>

	get(
		path: "/entry/organization/{organizationId}/product-sheets" | "/entry/organization/{organizationId}/edit-product-sheet/{productSheetId}" | "/entry/organization/{organizationId}/create-product-sheet", 
		parameters : parameters_8 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_8_0
		| response_8_1
		| response_8_2
		| response_8_3
		| response_8_4
	>

	get(
		path: "/entry/organization/{organizationId}*", 
		parameters : parameters_9 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_9_0
		| response_9_1
		| response_9_2
	>

	get(
		path: "/entry/login" | "/entry/register", 
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_10_0
	>

	patch(
		path: "/organization/{organizationId}/user/{userId}", 
		body: request_body_11,
		parameters : parameters_11 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_11_0
		| response_11_1
		| response_11_2
		| response_11_3
		| response_11_4
		| response_11_5
	>

	delete(
		path: "/organization/{organizationId}/user/{userId}", 
		parameters : parameters_12 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_12_0
		| response_12_1
		| response_12_2
		| response_12_3
		| response_12_4
		| response_12_5
	>

	post(
		path: "/category", 
		body: request_body_13,
		parameters : parameters_13 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_13_0
		| response_13_1
		| response_13_2
		| response_13_3
	>

	post(
		path: "/register", 
		body: request_body_14,
	post(
		path: "/register", 
		body: request_body_14,
		parameters : parameters_14 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_14_0
		| response_14_1
		| response_14_2
		| response_14_3
		| response_14_4
		| response_14_3
		| response_14_4
	>

	get(
		path: "/user", 
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_15_0
		| response_15_1
		| response_15_2
		| response_15_3
		| response_15_4
	>

	post(
		path: "/organization/{organizationId}/user", 
		body: request_body_16,
		parameters : parameters_16 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_16_0
		| response_16_1
		| response_16_2
		| response_16_3
		| response_16_4
		| response_16_5
		| response_16_6
	>

	get(
		path: "/organization/{organizationId}/user", 
		parameters : parameters_17 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_17_0
		| response_17_1
		| response_17_2
	>

	post(
		path: "/organization/{organizationId}/user", 
		body: request_body_18,
		parameters : parameters_18 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_18_0
		| response_18_1
		| response_18_2
		| response_18_3
		| response_18_4
		| response_18_5
		| response_18_6
	>

	post(
		path: "/category", 
		body: request_body_19,
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_19_0
		| response_19_1
		| response_19_2
		| response_19_3
	>

	patch(
		path: "/parent-category/{parentCategoryName}", 
		body: request_body_20,
		parameters : parameters_20 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_20_0
		| response_20_1
		| response_20_2
		| response_20_3
		| response_20_4
	>

	patch(
		path: "/organization/{organizationId}@admin", 
		body: request_body_21,
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_21_0
		| response_21_1
		| response_21_2
		| response_21_3
	>

	get(
		path: "/organizations", 
		parameters ?: parameters_22 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_22_0
		| response_22_1
		| response_22_2
	>

	delete(
		path: "/parent-category/{parentCategoryName}/category/{categoryName}", 
		parameters : parameters_23 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_23_0
		| response_23_1
		| response_23_2
		| response_23_3
	>

	patch(
		path: "/user/{userId}@admin", 
		body: request_body_24,
		parameters : parameters_24 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_24_0
		| response_24_1
		| response_24_2
	>

	get(
		path: "/users", 
		parameters ?: parameters_25 & BaseRequestParameters,
	get(
		path: "/users", 
		parameters ?: parameters_25 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_25_0
		| response_25_1
		| response_25_2
	>

	get(
		path: "/organization/{organizationId}/product-sheets", 
		parameters : parameters_26 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_26_0
		| response_26_1
		| response_26_2
		| response_26_3
		| response_26_4
	>

	post(
		path: "/organization/{organizationId}/product-sheet", 
		body: request_body_27,
		parameters : parameters_27 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_27_0
		| response_27_1
		| response_27_2
	>

	get(
		path: "/organization/{organizationId}/users", 
		parameters : parameters_28 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_28_0
		| response_28_1
		| response_28_2
		| response_28_3
		| response_28_4
		| response_28_5
	>

	post(
		path: "/organization/{organizationId}/warehouse", 
		body: request_body_29,
		parameters : parameters_29 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_29_0
		| response_29_1
		| response_29_2
		| response_29_3
		| response_29_4
		| response_29_5
		| response_29_4
		| response_29_5
	>

	patch(
		path: "/warehouse/{warehouseId}", 
		body: request_body_30,
		parameters : parameters_30 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_30_0
		| response_30_1
		| response_30_2
		| response_30_3
		| response_30_4
		| response_30_5
		| response_30_6
	>

	get(
		path: "/organization/{organizationId}/warehouses", 
		parameters : parameters_31 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_31_0
		| response_31_1
		| response_31_2
		| response_31_3
		| response_31_4
		| response_31_5
	>

	post(
		path: "/product-sheet/{productSheetId}/category", 
		body: request_body_32,
		parameters : parameters_32 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_32_0
		| response_32_1
		| response_32_2
	>

	get(
		path: "/product-sheet/{productSheetId}/categories", 
		parameters : parameters_33 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_33_0
		| response_33_1
		| response_33_2
		| response_33_3
		| response_33_4
		| response_33_5
		| response_33_6
	>

	delete(
		path: "/product-sheet/{productSheetId}/category/{categoryId}", 
		parameters : parameters_34 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_34_0
		| response_34_1
		| response_34_2
		| response_34_3
		| response_34_4
		| response_34_5
	>

	get(
		path: "/product-sheet/{productSheetId}", 
		parameters : parameters_35 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_35_0
		| response_35_1
		| response_35_2
		| response_35_3
		| response_35_4
	>

	patch(
		path: "/product-sheet/{productSheetId}", 
		body: request_body_36,
		parameters : parameters_36 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_36_0
		| response_36_1
		| response_36_2
		| response_36_3
		| response_36_4
		| response_36_5
	>

	get(
		path: "/product-sheet/{productSheetId}/images", 
		parameters : parameters_37 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_37_0
		| response_37_1
		| response_37_2
	>

	post(
		path: "/product-sheet/{productSheetId}/image", 
		body: unknown,
		parameters : parameters_38 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_38_0
		| response_38_1
		| response_38_2
		| response_38_3
		| response_38_4
		| response_38_5
		| response_38_6
	>

}

/** @deprecated */
export type EnrichedDuplojsTo<
	interceptorParameter extends {} = {},
> = EnrichedDuploTo<interceptorParameter>;
