
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by @duplojs/to

export type parameters_0 = {
    query?: {
        name?: string | undefined;
        page?: number;
        withDisabled?: boolean | undefined;
    };
}

export type response_body_0_0 = {
    name: string;
    disabled: boolean;
    imageKey: string | null;
    imageUrl: string | null;
}[]

export type response_0_0 = {
    code: 200;
    ok: true;
    info: "categories";
} & {body: response_body_0_0};

export type parameters_1 = {
    params: {
        categoryName: string;
    };
    query?: {
        page?: number;
    } | undefined;
}

export type response_1_0 = {
    code: 404;
    ok: false;
    info: "category.notfound";
} & {body: undefined};

export type response_body_1_1 = {
    id: string;
    name: string;
    description: string;
    shortDescription: string;
    price: number;
    createdAt?: string;
    updatedAt?: string;
    organizationId: string;
}[]

export type response_1_1 = {
    code: 200;
    ok: true;
    info: "category.products";
} & {body: response_body_1_1};

export type parameters_2 = {
    query?: {
        address?: string | undefined;
    } | undefined;
}

export type response_body_2_0 = string[]

export type response_2_0 = {
    code: 200;
    ok: true;
    info?: undefined;
} & {body: response_body_2_0};

export type response_3_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_3_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_3_2 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_4_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_4_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_4_2 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type parameters_5 = {
    params: {
        organizationId: string;
    };
}

export type response_5_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_5_1 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_5_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_5_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type parameters_6 = {
    params: {
        organizationId: string;
        warehouseId?: string | undefined;
    };
}

export type response_6_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_6_1 = {
    code: 401;
    ok: false;
    info: "entry.refuse";
} & {body: undefined};

export type response_6_2 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_6_3 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_6_4 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type parameters_7 = {
    params: {
        organizationId: string;
        productSheetId?: string | undefined;
    };
}

export type response_7_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_7_1 = {
    code: 401;
    ok: false;
    info: "entry.refuse";
} & {body: undefined};

export type response_7_2 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_7_3 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_7_4 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type parameters_8 = {
    params: {
        organizationId: string;
    };
}

export type response_8_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_8_1 = {
    code: 401;
    ok: false;
    info: "entry.refuse";
} & {body: undefined};

export type response_8_2 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_9_0 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_10_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_10_1 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_11_0 = {
    code: 204;
    ok: true;
    info: "entry.accepted";
} & {body: undefined};

export type response_body_12_0 = ({
    type: "PARENT_CATEGORY";
    parentCategoryName: string;
    categories: {
        categoryName: string;
        categoryImageUrl: string;
    }[];
} | {
    type: "CATEGORY";
    categoryName: string;
} | {
    type: "LINK";
    title: string;
    url: string;
})[]

export type response_12_0 = {
    code: 200;
    ok: true;
    info: "navigationBar";
} & {body: response_body_12_0};

export type request_body_13 = {
    fireBaseIdToken: string;
    lastname: string;
    firstname: string;
    address: string;
    dateOfBirth: Date;
}

export type response_13_0 = {
    code: 401;
    ok: false;
    info: "firebase.token.invalid";
} & {body: undefined};

export type response_13_1 = {
    code: 409;
    ok: false;
    info: "user.alreadyExist";
} & {body: undefined};

export type response_13_2 = {
    code: 400;
    ok: false;
    info: "user.address.invalid";
} & {body: undefined};

export type response_13_3 = {
    code: 400;
    ok: false;
    info: "user.dateOfBirth.invalid";
} & {body: undefined};

export type response_body_13_4 = string

export type response_13_4 = {
    code: 201;
    ok: true;
    info: "user.registered";
} & {body: response_body_13_4};

export type request_body_14 = string

export type response_14_0 = {
    code: 401;
    ok: false;
    info: "firebase.token.invalid";
} & {body: undefined};

export type response_14_1 = {
    code: 404;
    ok: false;
    info: "user.notfound";
} & {body: undefined};

export type response_body_14_2 = string

export type response_14_2 = {
    code: 200;
    ok: true;
    info: "user.logged";
} & {body: response_body_14_2};

export type request_body_15 = {
    organizationRole?: ("STORE_KEEPER" | "PRODUCT_SHEET_MANAGER" | "ACCOUNTANT") | undefined;
}

export type parameters_15 = {
    params: {
        organizationId: string;
        userId: string;
    };
}

export type response_15_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_15_1 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_15_2 = {
    code: 401;
    ok: false;
    info: "organization.user.organizationRole.owner";
} & {body: undefined};

export type response_15_3 = {
    code: 204;
    ok: true;
    info: "organization.user.edited";
} & {body: undefined};

export type response_15_4 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_15_5 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type parameters_16 = {
    params: {
        organizationId: string;
        userId: string;
    };
}

export type response_16_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_16_1 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_16_2 = {
    code: 401;
    ok: false;
    info: "organization.user.organizationRole.owner";
} & {body: undefined};

export type response_16_3 = {
    code: 204;
    ok: true;
    info: "organization.user.deleted";
} & {body: undefined};

export type response_16_4 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_16_5 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_17_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_17_1 = {
    code: 404;
    ok: false;
    info: "user.notfound";
} & {body: undefined};

export type response_body_17_2 = {
    id: string;
    email: string;
    lastname: string;
    firstname: string;
    dateOfBirth?: string;
    address: string;
    primordialRole: "CUSTOMER" | "MODERATOR" | "CONTENTS_MASTER" | "ADMIN";
    muted: boolean;
    hasOrganization: boolean;
}

export type response_17_2 = {
    code: 200;
    ok: true;
    info: "user";
} & {body: response_body_17_2};

export type request_body_18 = {
    lastname?: string | undefined;
    firstname?: string | undefined;
    address?: string | undefined;
}

export type response_18_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_18_1 = {
    code: 400;
    ok: false;
    info: "user.address.invalid";
} & {body: undefined};

export type response_body_18_2 = string

export type response_18_2 = {
    code: 201;
    ok: true;
    info: "user.edited";
} & {body: response_body_18_2};

export type parameters_19 = {
    params: {
        imageProductSheetId: string;
    };
}

export type response_19_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_19_1 = {
    code: 404;
    ok: false;
    info: "imageProductSheet.notfound";
} & {body: undefined};

export type response_19_2 = {
    code: 204;
    ok: true;
    info: "imageProductSheet.deleted";
} & {body: undefined};

export type response_19_3 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_19_4 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type parameters_20 = {
    params: {
        organizationId: string;
    };
}

export type response_20_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_20_1 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_body_20_2 = {
    id: string;
    email: string;
    lastname: string;
    firstname: string;
    organizationRole: "STORE_KEEPER" | "PRODUCT_SHEET_MANAGER" | "ACCOUNTANT" | "OWNER";
}

export type response_20_2 = {
    code: 200;
    ok: true;
    info: "organization.user";
} & {body: response_body_20_2};

export type request_body_21 = {
    email: string;
    firstname: string;
    lastname: string;
    organizationRole: "STORE_KEEPER" | "PRODUCT_SHEET_MANAGER" | "ACCOUNTANT";
}

export type parameters_21 = {
    params: {
        organizationId: string;
    };
}

export type response_21_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_21_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_21_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_21_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_21_4 = {
    code: 404;
    ok: false;
    info: "user.notfound";
} & {body: undefined};

export type response_21_5 = {
    code: 409;
    ok: false;
    info: "organization.hasAlreadyUser";
} & {body: undefined};

export type response_21_6 = {
    code: 201;
    ok: true;
    info: "organization.user.add";
} & {body: undefined};

export type parameters_22 = {
    query?: {
        page?: number;
    } | undefined;
}

export type response_22_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_22_1 = {
    code: 404;
    ok: false;
    info: "user.notfound";
} & {body: undefined};

export type response_body_22_2 = {
    id: string;
    name: string;
    label: string | null;
    ownerId: string;
    suspended: boolean;
    logoKey: string | null;
    logoUrl: string | null;
}[]

export type response_22_2 = {
    code: 200;
    ok: true;
    info: "user.organizations";
} & {body: response_body_22_2};

export type parameters_23 = {
    params: {
        productSheetId: string;
        categoryName: string;
    };
}

export type response_23_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_23_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_23_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_23_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_23_4 = {
    code: 404;
    ok: false;
    info: "category.notfound";
} & {body: undefined};

export type response_23_5 = {
    code: 200;
    ok: true;
    info: "productSheet.category.untied";
} & {body: undefined};

export type parameters_24 = {
    params: {
        productSheetId: string;
    };
}

export type response_24_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_24_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_24_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_24_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_24_4 = {
    id: string;
    name: string;
    description: string;
    shortDescription: string;
    price: number;
    createdAt?: string;
    updatedAt?: string;
    organizationId: string;
}

export type response_24_4 = {
    code: 200;
    ok: true;
    info: "productSheet.found";
} & {body: response_body_24_4};

export type request_body_25 = {
    name?: string | undefined;
    description?: string | undefined;
    shortDescription?: string | undefined;
    price?: number | undefined;
}

export type parameters_25 = {
    params: {
        productSheetId: string;
    };
}

export type response_25_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_25_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_25_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_25_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_25_4 = string

export type response_25_4 = {
    code: 201;
    ok: true;
    info: "productSheet.edited";
} & {body: response_body_25_4};

export type parameters_26 = {
    params: {
        productSheetId: string;
    };
}

export type response_26_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_26_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_26_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_26_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_26_4 = {
    name: string;
    disabled: boolean;
    imageKey: string | null;
    imageUrl: string | null;
}[]

export type response_26_4 = {
    code: 200;
    ok: true;
    info: "productSheet.categories";
} & {body: response_body_26_4};

export type request_body_27 = {
    type: "COLOR" | "SIZE" | "DIAMETER" | "TARGET" | "ACCESSORY" | "MATERIAL" | "STIMULATION";
    value: string;
}

export type parameters_27 = {
    params: {
        productSheetId: string;
    };
}

export type response_27_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_27_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_27_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_27_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_27_4 = {
    code: 409;
    ok: false;
    info: "productSheet.facet.alreadyExist";
} & {body: undefined};

export type response_body_27_5 = {
    type: "COLOR" | "SIZE" | "DIAMETER" | "TARGET" | "ACCESSORY" | "MATERIAL" | "STIMULATION";
    productSheetId: string;
    value: string;
}

export type response_27_5 = {
    code: 201;
    ok: true;
    info: "facet.created";
} & {body: response_body_27_5};

export type request_body_28 = {
    categoryName: string;
}

export type parameters_28 = {
    params: {
        productSheetId: string;
    };
}

export type response_28_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_28_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_28_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_28_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_28_4 = {
    code: 404;
    ok: false;
    info: "category.notfound";
} & {body: undefined};

export type response_28_5 = {
    code: 409;
    ok: false;
    info: "productSheet.categories.limit";
} & {body: undefined};

export type response_28_6 = {
    code: 200;
    ok: true;
    info: "productSheet.category.linked";
} & {body: undefined};

export type parameters_29 = {
    params: {
        productSheetId: string;
    };
}

export type response_29_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_29_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_29_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_29_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_29_4 = {
    type: "COLOR" | "SIZE" | "DIAMETER" | "TARGET" | "ACCESSORY" | "MATERIAL" | "STIMULATION";
    productSheetId: string;
    value: string;
}[]

export type response_29_4 = {
    code: 200;
    ok: true;
    info: "productSheet.facets";
} & {body: response_body_29_4};

export type request_body_30 = {
    value?: string | undefined;
}

export type parameters_30 = {
    params: {
        productSheetId: string;
        facetType: "COLOR" | "SIZE" | "DIAMETER" | "TARGET" | "ACCESSORY" | "MATERIAL" | "STIMULATION";
    };
}

export type response_30_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_30_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_30_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_30_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_30_4 = {
    code: 404;
    ok: false;
    info: "facet.notfound";
} & {body: undefined};

export type response_30_5 = {
    code: 204;
    ok: true;
    info: "facet.edited";
} & {body: undefined};

export type parameters_31 = {
    params: {
        productSheetId: string;
        facetType: "COLOR" | "SIZE" | "DIAMETER" | "TARGET" | "ACCESSORY" | "MATERIAL" | "STIMULATION";
    };
}

export type response_31_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_31_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_31_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_31_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_31_4 = {
    code: 404;
    ok: false;
    info: "facet.notfound";
} & {body: undefined};

export type response_31_5 = {
    code: 204;
    ok: true;
    info: "facet.deleted";
} & {body: undefined};

export type parameters_32 = {
    params: {
        productSheetId: string;
    };
}

export type response_32_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_32_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_32_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_32_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_32_4 = {
    id: string;
    productSheetId: string;
    organizationId: string;
    url: string;
    key: string;
    alt: string | null;
}[]

export type response_32_4 = {
    code: 200;
    ok: true;
    info: "productSheet.images";
} & {body: response_body_32_4};

export type parameters_33 = {
    headers: {
        "content-type": string;
        "content-length": number;
    };
    params: {
        productSheetId: string;
    };
}

export type response_33_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_33_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_33_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_33_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_33_4 = {
    code: 409;
    ok: false;
    info: "product.images.limit";
} & {body: undefined};

export type response_33_5 = {
    code: 400;
    ok: false;
    info: "productSheet.image.missing";
} & {body: undefined};

export type response_body_33_6 = {
    id: string;
    productSheetId: string;
    organizationId: string;
    url: string;
    key: string;
    alt: string | null;
}

export type response_33_6 = {
    code: 201;
    ok: true;
    info: "productSheet.image.create";
} & {body: response_body_33_6};

export type request_body_34 = {
    status?: ("IN_STOCK" | "WRONG") | undefined;
}

export type parameters_34 = {
    params: {
        sku: string;
    };
}

export type response_34_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_34_1 = {
    code: 404;
    ok: false;
    info: "product.notfound";
} & {body: undefined};

export type response_34_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_34_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_34_4 = {
    code: 204;
    ok: true;
    info: "product.edited";
} & {body: undefined};

export type request_body_35 = {
    name: string;
    description: string;
    shortDescription: string;
    price: number;
}

export type parameters_35 = {
    params: {
        organizationId: string;
    };
}

export type response_35_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_35_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_35_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_35_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_35_4 = {
    id: string;
    name: string;
    description: string;
    shortDescription: string;
    price: number;
    createdAt?: string;
    updatedAt?: string;
    organizationId: string;
}

export type response_35_4 = {
    code: 201;
    ok: true;
    info: "productSheet.created";
} & {body: response_body_35_4};

export type parameters_36 = {
    headers: {
        "content-type": string;
        "content-length": number;
    };
    params: {
        organizationId: string;
    };
}

export type response_36_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_36_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_36_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_36_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_36_4 = {
    code: 400;
    ok: false;
    info: "organization.logo.missing";
} & {body: undefined};

export type response_36_5 = {
    code: 204;
    ok: true;
    info: "organization.logo.edited";
} & {body: undefined};

export type request_body_37 = {
    sku: string;
    warehouseId: string;
}

export type parameters_37 = {
    params: {
        productSheetId: string;
    };
}

export type response_37_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_37_1 = {
    code: 404;
    ok: false;
    info: "productSheet.notfound";
} & {body: undefined};

export type response_37_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_37_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_37_4 = {
    code: 404;
    ok: false;
    info: "warehouse.notfound";
} & {body: undefined};

export type response_37_5 = {
    code: 409;
    ok: false;
    info: "product.sku.alreadyUse";
} & {body: undefined};

export type response_body_37_6 = {
    sku: string;
    productSheetId: string;
    organizationId: string;
    warehouseId: string;
    createdAt?: string;
    updatedAt?: string;
    status: "ORDER" | "WRONG" | "SOLD" | "IN_STOCK";
}

export type response_37_6 = {
    code: 201;
    ok: true;
    info: "product.created";
} & {body: response_body_37_6};

export type parameters_38 = {
    params: {
        organizationId: string;
    };
    query?: {
        page?: number;
        name?: string | undefined;
    } | undefined;
}

export type response_38_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_38_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_38_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_38_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_38_4 = {
    id: string;
    name: string;
    description: string;
    shortDescription: string;
    price: number;
    createdAt?: string;
    updatedAt?: string;
    organizationId: string;
}[]

export type response_38_4 = {
    code: 200;
    ok: true;
    info: "productSheets.found";
} & {body: response_body_38_4};

export type parameters_39 = {
    params: {
        organizationId: string;
    };
}

export type response_39_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_39_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_39_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_39_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_39_4 = {
    id: string;
    name: string;
    label: string | null;
    ownerId: string;
    suspended: boolean;
    logoKey: string | null;
    logoUrl: string | null;
}

export type response_39_4 = {
    code: 200;
    ok: true;
    info: "organization.found";
} & {body: response_body_39_4};

export type request_body_40 = {
    label?: (string | null) | undefined;
}

export type parameters_40 = {
    params: {
        organizationId: string;
    };
}

export type response_40_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_40_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_40_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_40_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_40_4 = {
    code: 204;
    ok: true;
    info: "organization.edited";
} & {body: undefined};

export type parameters_41 = {
    params: {
        organizationId: string;
    };
    query?: {
        page?: number;
        name?: string | undefined;
    } | undefined;
}

export type response_41_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_41_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_41_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_41_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_41_4 = {
    id: string;
    name: string;
    address: string;
    organizationId: string;
}[]

export type response_41_4 = {
    code: 200;
    ok: true;
    info: "warehouses.found";
} & {body: response_body_41_4};

export type parameters_42 = {
    params: {
        organizationId: string;
    };
    query?: {
        page?: number;
        email?: string | undefined;
    } | undefined;
}

export type response_42_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_42_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_42_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_42_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_42_4 = {
    id: string;
    email: string;
    lastname: string;
    firstname: string;
    organizationRole: "STORE_KEEPER" | "PRODUCT_SHEET_MANAGER" | "ACCOUNTANT" | "OWNER";
}[]

export type response_42_4 = {
    code: 200;
    ok: true;
    info: "organization.users";
} & {body: response_body_42_4};

export type parameters_43 = {
    params: {
        organizationId: string;
    };
    query?: {
        page?: number;
        sku?: string | undefined;
        withProductSheet?: ("true" | "false") | undefined;
        withWarehouse?: ("true" | "false") | undefined;
    } | undefined;
}

export type response_43_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_43_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_43_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_43_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_body_43_4 = {
    sku: string;
    productSheetId: string;
    organizationId: string;
    warehouseId: string;
    createdAt?: string;
    updatedAt?: string;
    status: "ORDER" | "WRONG" | "SOLD" | "IN_STOCK";
    productSheet?: {
        id: string;
        name: string;
        description: string;
        shortDescription: string;
        price: number;
        createdAt?: string;
        updatedAt?: string;
        organizationId: string;
    } | undefined;
    warehouse?: {
        id: string;
        name: string;
        address: string;
        organizationId: string;
    } | undefined;
}[]

export type response_43_4 = {
    code: 200;
    ok: true;
    info: "products.found";
} & {body: response_body_43_4};

export type request_body_44 = {
    name: string;
    address: string;
}

export type parameters_44 = {
    params: {
        organizationId: string;
    };
}

export type response_44_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_44_1 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_44_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_44_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_44_4 = {
    code: 400;
    ok: false;
    info: "warehouse.address.invalid";
} & {body: undefined};

export type response_body_44_5 = {
    id: string;
    name: string;
    address: string;
    organizationId: string;
}

export type response_44_5 = {
    code: 201;
    ok: true;
    info: "warehouse.created";
} & {body: response_body_44_5};

export type request_body_45 = {
    name: string;
    disabled: boolean;
}

export type response_45_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_45_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_45_2 = {
    code: 409;
    ok: false;
    info: "category.alreadyExist";
} & {body: undefined};

export type response_body_45_3 = {
    name: string;
    disabled: boolean;
    imageKey: string | null;
    imageUrl: string | null;
}

export type response_45_3 = {
    code: 201;
    ok: true;
    info: "category.created";
} & {body: response_body_45_3};

export type request_body_46 = {
    name: string;
    ownerId: string;
}

export type response_46_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_46_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_46_2 = {
    code: 409;
    ok: false;
    info: "organization.alreadyExist";
} & {body: undefined};

export type response_46_3 = {
    code: 404;
    ok: false;
    info: "user.notfound";
} & {body: undefined};

export type response_46_4 = {
    code: 409;
    ok: false;
    info: "user.alreadyOwner";
} & {body: undefined};

export type response_46_5 = {
    code: 201;
    ok: true;
    info: "organization.created";
} & {body: undefined};

export type parameters_47 = {
    headers: {
        "content-type": string;
        "content-length": number;
    };
    params: {
        categoryName: string;
    };
}

export type response_47_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_47_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_47_2 = {
    code: 404;
    ok: false;
    info: "category.notfound";
} & {body: undefined};

export type response_47_3 = {
    code: 400;
    ok: false;
    info: "category.image.missing";
} & {body: undefined};

export type response_47_4 = {
    code: 204;
    ok: true;
    info: "category.image.updated";
} & {body: undefined};

export type request_body_48 = {
    suspended?: boolean | undefined;
}

export type parameters_48 = {
    params: {
        organizationId: string;
    };
}

export type response_48_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_48_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_48_2 = {
    code: 404;
    ok: false;
    info: "organization.notfound";
} & {body: undefined};

export type response_48_3 = {
    code: 204;
    ok: true;
    info: "organization.edited";
} & {body: undefined};

export type request_body_49 = {
    name?: string | undefined;
    disabled?: boolean | undefined;
} | undefined

export type parameters_49 = {
    params: {
        categoryName: string;
    };
}

export type response_49_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_49_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_49_2 = {
    code: 404;
    ok: false;
    info: "category.notfound";
} & {body: undefined};

export type response_49_3 = {
    code: 409;
    ok: false;
    info: "category.alreadyExist";
} & {body: undefined};

export type response_49_4 = {
    code: 204;
    ok: true;
    info: "category.edited";
} & {body: undefined};

export type request_body_50 = {
    priority: number;
    type: "PARENT_CATEGORY";
    parentCategoryName: string;
} | {
    priority: number;
    type: "CATEGORY";
    categoryName: string;
} | {
    priority: number;
    type: "LINK";
    url: string;
    title: string;
}

export type response_50_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_50_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_50_2 = {
    code: 409;
    ok: false;
    info: "navigationItem.limit";
} & {body: undefined};

export type response_body_50_3 = {
    id: string;
    priority: number;
    type: "PARENT_CATEGORY";
    parentCategoryName: string;
} | {
    id: string;
    priority: number;
    type: "CATEGORY";
    categoryName: string;
} | {
    id: string;
    priority: number;
    type: "LINK";
    url: string;
    title: string;
}

export type response_50_3 = {
    code: 201;
    ok: true;
    info: "navigationItem.created";
} & {body: response_body_50_3};

export type response_51_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_51_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_body_51_2 = ({
    id: string;
    priority: number;
    type: "PARENT_CATEGORY";
    parentCategoryName: string;
} | {
    id: string;
    priority: number;
    type: "CATEGORY";
    categoryName: string;
} | {
    id: string;
    priority: number;
    type: "LINK";
    url: string;
    title: string;
})[]

export type response_51_2 = {
    code: 200;
    ok: true;
    info: "navigationItems";
} & {body: response_body_51_2};

export type request_body_52 = {
    id: string;
    priority: number;
    type: "PARENT_CATEGORY";
    parentCategoryName: string;
} | {
    id: string;
    priority: number;
    type: "CATEGORY";
    categoryName: string;
} | {
    id: string;
    priority: number;
    type: "LINK";
    url: string;
    title: string;
}

export type parameters_52 = {
    params: {
        navigationItemId: string;
    };
}

export type response_52_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_52_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_52_2 = {
    code: 404;
    ok: false;
    info: "navigationItem.notfound";
} & {body: undefined};

export type response_52_3 = {
    code: 404;
    ok: false;
    info: "category.notfound";
} & {body: undefined};

export type response_52_4 = {
    code: 404;
    ok: false;
    info: "parentCategory.notfound";
} & {body: undefined};

export type response_52_5 = {
    code: 204;
    ok: true;
    info: "navigationItem.edited";
} & {body: undefined};

export type parameters_53 = {
    params: {
        navigationItemId: string;
    };
}

export type response_53_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_53_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_53_2 = {
    code: 404;
    ok: false;
    info: "navigationItem.notfound";
} & {body: undefined};

export type response_53_3 = {
    code: 204;
    ok: true;
    info: "navigationItem.delete";
} & {body: undefined};

export type parameters_54 = {
    params: {
        parentCategoryName: string;
    };
}

export type response_54_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_54_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_54_2 = {
    code: 404;
    ok: false;
    info: "parentCategory.notfound";
} & {body: undefined};

export type response_body_54_3 = {
    name: string;
    disabled: boolean;
    imageKey: string | null;
    imageUrl: string | null;
}[]

export type response_54_3 = {
    code: 200;
    ok: true;
    info: "parentCategory.categories";
} & {body: response_body_54_3};

export type request_body_55 = {
    categoryName: string;
}

export type parameters_55 = {
    params: {
        parentCategoryName: string;
    };
}

export type response_55_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_55_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_55_2 = {
    code: 404;
    ok: false;
    info: "parentCategory.notfound";
} & {body: undefined};

export type response_55_3 = {
    code: 404;
    ok: false;
    info: "category.notfound";
} & {body: undefined};

export type response_55_4 = {
    code: 409;
    ok: false;
    info: "parentCategory.categories.limit";
} & {body: undefined};

export type response_55_5 = {
    code: 204;
    ok: true;
    info: "parentCategory.category.linked";
} & {body: undefined};

export type parameters_56 = {
    query?: {
        page?: number;
        name?: string | undefined;
    } | undefined;
}

export type response_56_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_56_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_body_56_2 = {
    id: string;
    name: string;
    label: string | null;
    ownerId: string;
    suspended: boolean;
    logoKey: string | null;
    logoUrl: string | null;
}[]

export type response_56_2 = {
    code: 200;
    ok: true;
    info: "organizations";
} & {body: response_body_56_2};

export type request_body_57 = {
    name?: string | undefined;
}

export type parameters_57 = {
    params: {
        parentCategoryName: string;
    };
}

export type response_57_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_57_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_57_2 = {
    code: 404;
    ok: false;
    info: "parentCategory.notfound";
} & {body: undefined};

export type response_57_3 = {
    code: 409;
    ok: false;
    info: "parentCategory.name.alreadyUse";
} & {body: undefined};

export type response_57_4 = {
    code: 204;
    ok: true;
    info: "parentCategory.edited";
} & {body: undefined};

export type request_body_58 = {
    name: string;
}

export type response_58_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_58_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_58_2 = {
    code: 409;
    ok: false;
    info: "parentCategory.name.alreadyUse";
} & {body: undefined};

export type response_body_58_3 = {
    name: string;
}

export type response_58_3 = {
    code: 201;
    ok: true;
    info: "parentCategory.created";
} & {body: response_body_58_3};

export type parameters_59 = {
    query?: {
        page?: number;
        email?: string | undefined;
        primordialRole?: (("CUSTOMER" | "MODERATOR" | "CONTENTS_MASTER" | "ADMIN") | ("CUSTOMER" | "MODERATOR" | "CONTENTS_MASTER" | "ADMIN")[]) | undefined;
    } | undefined;
}

export type response_59_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_59_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_body_59_2 = {
    id: string;
    email: string;
    lastname: string;
    firstname: string;
    dateOfBirth?: string;
    address: string;
    primordialRole: "CUSTOMER" | "MODERATOR" | "CONTENTS_MASTER" | "ADMIN";
    muted: boolean;
}[]

export type response_59_2 = {
    code: 200;
    ok: true;
    info: "users";
} & {body: response_body_59_2};

export type request_body_60 = {
    primordialRole?: ("CUSTOMER" | "CONTENTS_MASTER" | "MODERATOR") | undefined;
    muted?: boolean | undefined;
}

export type parameters_60 = {
    params: {
        userId: string;
    };
}

export type response_60_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_60_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_60_2 = {
    code: 404;
    ok: false;
    info: "user.notfound";
} & {body: undefined};

export type response_60_3 = {
    code: 401;
    ok: false;
    info: "user.primordialRole.admin";
} & {body: undefined};

export type response_60_4 = {
    code: 204;
    ok: true;
    info: "user.edited";
} & {body: undefined};

export type parameters_61 = {
    params: {
        parentCategoryName: string;
        categoryName: string;
    };
}

export type response_61_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_61_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_61_2 = {
    code: 404;
    ok: false;
    info: "parentCategory.notfound";
} & {body: undefined};

export type response_61_3 = {
    code: 200;
    ok: true;
    info: "parentCategory.category.untied";
} & {body: undefined};

export type request_body_62 = {
    name?: string | undefined;
    address?: string | undefined;
}

export type parameters_62 = {
    params: {
        warehouseId: string;
    };
}

export type response_62_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_62_1 = {
    code: 404;
    ok: false;
    info: "warehouse.notfound";
} & {body: undefined};

export type response_62_2 = {
    code: 406;
    ok: false;
    info: "organization.hasNotUser";
} & {body: undefined};

export type response_62_3 = {
    code: 403;
    ok: false;
    info: "user.role.organization.invalid";
} & {body: undefined};

export type response_62_4 = {
    code: 400;
    ok: false;
    info: "warehouse.address.invalid";
} & {body: undefined};

export type response_62_5 = {
    code: 204;
    ok: true;
    info: "warehouse.edited";
} & {body: undefined};

export type parameters_63 = {
    query?: {
        page?: number;
        name?: string | undefined;
        withCategories?: ("true" | "false") | undefined;
    } | undefined;
}

export type response_63_0 = {
    code: 401;
    ok: false;
    info: "access.token.invalid";
} & {body: undefined};

export type response_63_1 = {
    code: 403;
    ok: false;
    info: "user.role.invalid";
} & {body: undefined};

export type response_body_63_2 = {
    name: string;
    categories?: {
        categoryName: string;
    }[] | undefined;
}[]

export type response_63_2 = {
    code: 200;
    ok: true;
    info: "parentCategories";
} & {body: response_body_63_2};

export type parameters_64 = {
    params: {
        id: string;
    };
}

export type response_64_0 = {
    code: 404;
    ok: false;
    info: "fullProductSheet.notfound";
} & {body: undefined};

export type response_body_64_1 = {
    id: string;
    name: string;
    price: number;
    shortDescription: string;
    description: string;
    quantity: number;
    categories: string[];
    images: string[];
    organization: {
        id: string;
        name: string;
        label?: string | undefined;
        logoUrl?: string | undefined;
    };
    facets: {
        ACCESSORY?: string | undefined;
        COLOR?: string | undefined;
        DIAMETER?: string | undefined;
        MATERIAL?: string | undefined;
        SIZE?: string | undefined;
        STIMULATION?: string | undefined;
        TARGET?: string | undefined;
    };
}

export type response_64_1 = {
    code: 200;
    ok: true;
    info: "fullProductSheet";
} & {body: response_body_64_1};

export type parameters_65 = {
    query?: {
        page?: number;
    };
}

export type response_body_65_0 = {
    id: string;
    name: string;
    price: number;
    shortDescription: string;
    description: string;
    quantity: number;
    categories: string[];
    images: string[];
    organization: {
        id: string;
        name: string;
        label?: string | undefined;
        logoUrl?: string | undefined;
    };
    facets: {
        ACCESSORY?: string | undefined;
        COLOR?: string | undefined;
        DIAMETER?: string | undefined;
        MATERIAL?: string | undefined;
        SIZE?: string | undefined;
        STIMULATION?: string | undefined;
        TARGET?: string | undefined;
    };
}[]

export type response_65_0 = {
    code: 200;
    ok: true;
    info: "fullProductSheets";
} & {body: response_body_65_0};

export type GetDef<
	method extends DefEnrichedDuplojsTo["method"],
	path extends Extract<
		DefEnrichedDuplojsTo, 
		{method: method}
	>["path"] = any, 
> = Extract<
	DefEnrichedDuplojsTo, 
	{
		method: method,
		path: path
	}
>;

export type DefDefinition = {
	path: string,
	method: string,
	body: unknown,
	parameters: unknown,
	response: ResponseDefinition,
}

export type GetResponseByInfo<
	def extends DefDefinition,
	info extends def["response"]["info"]
> = Extract<
	def["response"], 
	{
		info: info
	}
>;

export type GetResponseByCode<
	def extends DefDefinition,
	code extends def["response"]["code"]
> = Extract<
	def["response"], 
	{
		code: code
	}
>;

export type DefEnrichedDuplojsTo = {
	path: "/categories",
	method: "GET",
	body: unknown,
	parameters: parameters_0,
	response: response_0_0,
} | {
	path: "/category/{categoryName}/product-sheets",
	method: "GET",
	body: unknown,
	parameters: parameters_1,
	response: response_1_0
		| response_1_1,
} | {
	path: "/geocoder",
	method: "GET",
	body: unknown,
	parameters: parameters_2,
	response: response_2_0,
} | {
	path: "/entry/admin-panel*",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_3_0
		| response_3_1
		| response_3_2,
} | {
	path: "/entry/content-panel*",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_4_0
		| response_4_1
		| response_4_2,
} | {
	path: "/entry/organization-panel/{organizationId}/manage-user" | "/entry/organization-panel/{organizationId}/manage",
	method: "GET",
	body: unknown,
	parameters: parameters_5,
	response: response_5_0
		| response_5_1
		| response_5_2
		| response_5_3,
} | {
	path: "/entry/organization-panel/{organizationId}/warehouses" | "/entry/organization-panel/{organizationId}/create-warehouse" | "/entry/organization-panel/{organizationId}/edited-warehouse/{warehouseId}",
	method: "GET",
	body: unknown,
	parameters: parameters_6,
	response: response_6_0
		| response_6_1
		| response_6_2
		| response_6_3
		| response_6_4,
} | {
	path: "/entry/organization-panel/{organizationId}/product-sheets" | "/entry/organization-panel/{organizationId}/edit-product-sheet/{productSheetId}" | "/entry/organization-panel/{organizationId}/create-product-sheet",
	method: "GET",
	body: unknown,
	parameters: parameters_7,
	response: response_7_0
		| response_7_1
		| response_7_2
		| response_7_3
		| response_7_4,
} | {
	path: "/entry/organization-panel/{organizationId}*",
	method: "GET",
	body: unknown,
	parameters: parameters_8,
	response: response_8_0
		| response_8_1
		| response_8_2,
} | {
	path: "/entry/login" | "/entry/register",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_9_0,
} | {
	path: "/entry/edit-profile" | "/entry/my-organizations",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_10_0
		| response_10_1,
} | {
	path: "/entry*",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_11_0,
} | {
	path: "/navigation-bar",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_12_0,
} | {
	path: "/register",
	method: "POST",
	body: request_body_13,
	parameters: undefined,
	response: response_13_0
		| response_13_1
		| response_13_2
		| response_13_3
		| response_13_4,
} | {
	path: "/login",
	method: "POST",
	body: request_body_14,
	parameters: undefined,
	response: response_14_0
		| response_14_1
		| response_14_2,
} | {
	path: "/organization/{organizationId}/user/{userId}",
	method: "PATCH",
	body: request_body_15,
	parameters: parameters_15,
	response: response_15_0
		| response_15_1
		| response_15_2
		| response_15_3
		| response_15_4
		| response_15_5,
} | {
	path: "/organization/{organizationId}/user/{userId}",
	method: "DELETE",
	body: unknown,
	parameters: parameters_16,
	response: response_16_0
		| response_16_1
		| response_16_2
		| response_16_3
		| response_16_4
		| response_16_5,
} | {
	path: "/user",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_17_0
		| response_17_1
		| response_17_2,
} | {
	path: "/user",
	method: "PATCH",
	body: request_body_18,
	parameters: undefined,
	response: response_18_0
		| response_18_1
		| response_18_2,
} | {
	path: "/image-product-sheet/{imageProductSheetId}",
	method: "DELETE",
	body: unknown,
	parameters: parameters_19,
	response: response_19_0
		| response_19_1
		| response_19_2
		| response_19_3
		| response_19_4,
} | {
	path: "/organization/{organizationId}/user",
	method: "GET",
	body: unknown,
	parameters: parameters_20,
	response: response_20_0
		| response_20_1
		| response_20_2,
} | {
	path: "/organization/{organizationId}/user",
	method: "POST",
	body: request_body_21,
	parameters: parameters_21,
	response: response_21_0
		| response_21_1
		| response_21_2
		| response_21_3
		| response_21_4
		| response_21_5
		| response_21_6,
} | {
	path: "/user/organizations",
	method: "GET",
	body: unknown,
	parameters: parameters_22,
	response: response_22_0
		| response_22_1
		| response_22_2,
} | {
	path: "/product-sheet/{productSheetId}/category/{categoryName}",
	method: "DELETE",
	body: unknown,
	parameters: parameters_23,
	response: response_23_0
		| response_23_1
		| response_23_2
		| response_23_3
		| response_23_4
		| response_23_5,
} | {
	path: "/product-sheet/{productSheetId}",
	method: "GET",
	body: unknown,
	parameters: parameters_24,
	response: response_24_0
		| response_24_1
		| response_24_2
		| response_24_3
		| response_24_4,
} | {
	path: "/product-sheet/{productSheetId}",
	method: "PATCH",
	body: request_body_25,
	parameters: parameters_25,
	response: response_25_0
		| response_25_1
		| response_25_2
		| response_25_3
		| response_25_4,
} | {
	path: "/product-sheet/{productSheetId}/categories",
	method: "GET",
	body: unknown,
	parameters: parameters_26,
	response: response_26_0
		| response_26_1
		| response_26_2
		| response_26_3
		| response_26_4,
} | {
	path: "/product-sheet/{productSheetId}/facet",
	method: "POST",
	body: request_body_27,
	parameters: parameters_27,
	response: response_27_0
		| response_27_1
		| response_27_2
		| response_27_3
		| response_27_4
		| response_27_5,
} | {
	path: "/product-sheet/{productSheetId}/category",
	method: "POST",
	body: request_body_28,
	parameters: parameters_28,
	response: response_28_0
		| response_28_1
		| response_28_2
		| response_28_3
		| response_28_4
		| response_28_5
		| response_28_6,
} | {
	path: "/product-sheet/{productSheetId}/facets",
	method: "GET",
	body: unknown,
	parameters: parameters_29,
	response: response_29_0
		| response_29_1
		| response_29_2
		| response_29_3
		| response_29_4,
} | {
	path: "/product-sheet/{productSheetId}/facet/{facetType}",
	method: "PATCH",
	body: request_body_30,
	parameters: parameters_30,
	response: response_30_0
		| response_30_1
		| response_30_2
		| response_30_3
		| response_30_4
		| response_30_5,
} | {
	path: "/product-sheet/{productSheetId}/facet/{facetType}",
	method: "DELETE",
	body: unknown,
	parameters: parameters_31,
	response: response_31_0
		| response_31_1
		| response_31_2
		| response_31_3
		| response_31_4
		| response_31_5,
} | {
	path: "/product-sheet/{productSheetId}/images",
	method: "GET",
	body: unknown,
	parameters: parameters_32,
	response: response_32_0
		| response_32_1
		| response_32_2
		| response_32_3
		| response_32_4,
} | {
	path: "/product-sheet/{productSheetId}/image",
	method: "POST",
	body: unknown,
	parameters: parameters_33,
	response: response_33_0
		| response_33_1
		| response_33_2
		| response_33_3
		| response_33_4
		| response_33_5
		| response_33_6,
} | {
	path: "/product/{sku}",
	method: "PATCH",
	body: request_body_34,
	parameters: parameters_34,
	response: response_34_0
		| response_34_1
		| response_34_2
		| response_34_3
		| response_34_4,
} | {
	path: "/organization/{organizationId}/product-sheet",
	method: "POST",
	body: request_body_35,
	parameters: parameters_35,
	response: response_35_0
		| response_35_1
		| response_35_2
		| response_35_3
		| response_35_4,
} | {
	path: "/organization/{organizationId}/logo",
	method: "PUT",
	body: unknown,
	parameters: parameters_36,
	response: response_36_0
		| response_36_1
		| response_36_2
		| response_36_3
		| response_36_4
		| response_36_5,
} | {
	path: "/product-sheet/{productSheetId}/product",
	method: "POST",
	body: request_body_37,
	parameters: parameters_37,
	response: response_37_0
		| response_37_1
		| response_37_2
		| response_37_3
		| response_37_4
		| response_37_5
		| response_37_6,
} | {
	path: "/organization/{organizationId}/product-sheets",
	method: "GET",
	body: unknown,
	parameters: parameters_38,
	response: response_38_0
		| response_38_1
		| response_38_2
		| response_38_3
		| response_38_4,
} | {
	path: "/organization/{organizationId}",
	method: "GET",
	body: unknown,
	parameters: parameters_39,
	response: response_39_0
		| response_39_1
		| response_39_2
		| response_39_3
		| response_39_4,
} | {
	path: "/organization/{organizationId}",
	method: "PATCH",
	body: request_body_40,
	parameters: parameters_40,
	response: response_40_0
		| response_40_1
		| response_40_2
		| response_40_3
		| response_40_4,
} | {
	path: "/organization/{organizationId}/warehouses",
	method: "GET",
	body: unknown,
	parameters: parameters_41,
	response: response_41_0
		| response_41_1
		| response_41_2
		| response_41_3
		| response_41_4,
} | {
	path: "/organization/{organizationId}/users",
	method: "GET",
	body: unknown,
	parameters: parameters_42,
	response: response_42_0
		| response_42_1
		| response_42_2
		| response_42_3
		| response_42_4,
} | {
	path: "/organization/{organizationId}/products",
	method: "GET",
	body: unknown,
	parameters: parameters_43,
	response: response_43_0
		| response_43_1
		| response_43_2
		| response_43_3
		| response_43_4,
} | {
	path: "/organization/{organizationId}/warehouse",
	method: "POST",
	body: request_body_44,
	parameters: parameters_44,
	response: response_44_0
		| response_44_1
		| response_44_2
		| response_44_3
		| response_44_4
		| response_44_5,
} | {
	path: "/category",
	method: "POST",
	body: request_body_45,
	parameters: undefined,
	response: response_45_0
		| response_45_1
		| response_45_2
		| response_45_3,
} | {
	path: "/organization",
	method: "POST",
	body: request_body_46,
	parameters: undefined,
	response: response_46_0
		| response_46_1
		| response_46_2
		| response_46_3
		| response_46_4
		| response_46_5,
} | {
	path: "/category/{categoryName}/image",
	method: "PUT",
	body: unknown,
	parameters: parameters_47,
	response: response_47_0
		| response_47_1
		| response_47_2
		| response_47_3
		| response_47_4,
} | {
	path: "/organization/{organizationId}@admin",
	method: "PATCH",
	body: request_body_48,
	parameters: parameters_48,
	response: response_48_0
		| response_48_1
		| response_48_2
		| response_48_3,
} | {
	path: "/category/{categoryName}",
	method: "PATCH",
	body: request_body_49,
	parameters: parameters_49,
	response: response_49_0
		| response_49_1
		| response_49_2
		| response_49_3
		| response_49_4,
} | {
	path: "/navigation-item",
	method: "POST",
	body: request_body_50,
	parameters: undefined,
	response: response_50_0
		| response_50_1
		| response_50_2
		| response_50_3,
} | {
	path: "/navigation-items",
	method: "GET",
	body: unknown,
	parameters: undefined,
	response: response_51_0
		| response_51_1
		| response_51_2,
} | {
	path: "/navigation-item/{navigationItemId}",
	method: "PATCH",
	body: request_body_52,
	parameters: parameters_52,
	response: response_52_0
		| response_52_1
		| response_52_2
		| response_52_3
		| response_52_4
		| response_52_5,
} | {
	path: "/navigation-item/{navigationItemId}",
	method: "DELETE",
	body: unknown,
	parameters: parameters_53,
	response: response_53_0
		| response_53_1
		| response_53_2
		| response_53_3,
} | {
	path: "/parent-category/{parentCategoryName}/categories",
	method: "GET",
	body: unknown,
	parameters: parameters_54,
	response: response_54_0
		| response_54_1
		| response_54_2
		| response_54_3,
} | {
	path: "/parent-category/{parentCategoryName}/category",
	method: "POST",
	body: request_body_55,
	parameters: parameters_55,
	response: response_55_0
		| response_55_1
		| response_55_2
		| response_55_3
		| response_55_4
		| response_55_5,
} | {
	path: "/organizations",
	method: "GET",
	body: unknown,
	parameters: parameters_56,
	response: response_56_0
		| response_56_1
		| response_56_2,
} | {
	path: "/parent-category/{parentCategoryName}",
	method: "PATCH",
	body: request_body_57,
	parameters: parameters_57,
	response: response_57_0
		| response_57_1
		| response_57_2
		| response_57_3
		| response_57_4,
} | {
	path: "/parent-category",
	method: "POST",
	body: request_body_58,
	parameters: undefined,
	response: response_58_0
		| response_58_1
		| response_58_2
		| response_58_3,
} | {
	path: "/users",
	method: "GET",
	body: unknown,
	parameters: parameters_59,
	response: response_59_0
		| response_59_1
		| response_59_2,
} | {
	path: "/user/{userId}@admin",
	method: "PATCH",
	body: request_body_60,
	parameters: parameters_60,
	response: response_60_0
		| response_60_1
		| response_60_2
		| response_60_3
		| response_60_4,
} | {
	path: "/parent-category/{parentCategoryName}/category/{categoryName}",
	method: "DELETE",
	body: unknown,
	parameters: parameters_61,
	response: response_61_0
		| response_61_1
		| response_61_2
		| response_61_3,
} | {
	path: "/warehouse/{warehouseId}",
	method: "PATCH",
	body: request_body_62,
	parameters: parameters_62,
	response: response_62_0
		| response_62_1
		| response_62_2
		| response_62_3
		| response_62_4
		| response_62_5,
} | {
	path: "/parent-categories",
	method: "GET",
	body: unknown,
	parameters: parameters_63,
	response: response_63_0
		| response_63_1
		| response_63_2,
} | {
	path: "/full-product-sheet/{id}",
	method: "GET",
	body: unknown,
	parameters: parameters_64,
	response: response_64_0
		| response_64_1,
} | {
	path: "/full-product-sheets",
	method: "GET",
	body: unknown,
	parameters: parameters_65,
	response: response_65_0,
};


export type BaseRequestParameters = {
	disabledPrefix?: boolean,
} & Omit<RequestInit, "headers" | "method">;

export type UndefinedRequestParameters = {
	headers?: string | string[];
}

export type DefToArgumentsWithInfo<
	responseDefinition extends ResponseDefinition
> = responseDefinition extends ResponseDefinition 
	? [data: responseDefinition["body"], info: responseDefinition["info"]]
	: never

export type DefToArgumentsWithCode<
	responseDefinition extends ResponseDefinition
> = responseDefinition extends ResponseDefinition 
	? [data: responseDefinition["body"], code: responseDefinition["code"]]
	: never

export type RequestCallbackError = (error: Error) => void

export type ResponseObjectError = {
	success: false,
	error: Error,
}

export interface ResponseDefinition {
	code: number;
	ok: boolean;
	info?: string;
	body?: any;
}

export type RepDefToResponseObject<repDef extends ResponseDefinition> = 
	repDef extends ResponseDefinition 
		? {
			success: true,
			response: Response,
			data: repDef["body"],
			info: repDef["info"],
			code: repDef["code"]
		}
		: never

export declare class EnrichedRequestor<
	repDef extends ResponseDefinition
>{

	s(cb: (data: Extract<repDef, {ok: true}>["body"]) => void): this;
	sd(): Promise<
		Extract<repDef, {ok: true}>["body"]
	>;

	e(cb: (data: Extract<repDef, {ok: false}>["body"]) => void): this;
	ed(): Promise<
		Extract<repDef, {ok: false}>["body"]
	>;

	info<_info extends repDef["info"]>(
		info: _info | _info[],
		cb: (...args: DefToArgumentsWithInfo<Extract<repDef, {info: _info}>>) => void
	): this;
	id<_info extends repDef["info"]>(info: _info | _info[]): Promise<
		Extract<repDef, {info: _info}>["body"]
	>;

	code<_code extends repDef["code"]>(
		code: _code | _code[],
		cb: (...args: DefToArgumentsWithCode<Extract<repDef, {code: _code}>>) => void
	): this;
	cd<_code extends repDef["code"]>(code: _code | _code[]): Promise<
		Extract<repDef, {code: _code}>["body"]
	>;

	then(cb: (response: RepDefToResponseObject<repDef>) => void): this;
	catch(cb: RequestCallbackError): this;
	finally(cb: (response: RepDefToResponseObject<repDef> | ResponseObjectError) => void): this;
	result: Promise<
		| RepDefToResponseObject<repDef>
		| ResponseObjectError
	>;
}

export interface EnrichedDuploTo<
	interceptorParameter extends {} = {},
>{
	
	get(
		path: "/categories", 
		parameters ?: parameters_0 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_0_0
	>

	get(
		path: "/category/{categoryName}/product-sheets", 
		parameters : parameters_1 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_1_0
		| response_1_1
	>

	get(
		path: "/geocoder", 
		parameters ?: parameters_2 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_2_0
	>

	get(
		path: "/entry/admin-panel*", 
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_3_0
		| response_3_1
		| response_3_2
	>

	get(
		path: "/entry/content-panel*", 
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_4_0
		| response_4_1
		| response_4_2
	>

	get(
		path: "/entry/organization-panel/{organizationId}/manage-user" | "/entry/organization-panel/{organizationId}/manage", 
		parameters : parameters_5 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_5_0
		| response_5_1
		| response_5_2
		| response_5_3
	>

	get(
		path: "/entry/organization-panel/{organizationId}/warehouses" | "/entry/organization-panel/{organizationId}/create-warehouse" | "/entry/organization-panel/{organizationId}/edited-warehouse/{warehouseId}", 
		parameters : parameters_6 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_6_0
		| response_6_1
		| response_6_2
		| response_6_3
		| response_6_4
	>

	get(
		path: "/entry/organization-panel/{organizationId}/product-sheets" | "/entry/organization-panel/{organizationId}/edit-product-sheet/{productSheetId}" | "/entry/organization-panel/{organizationId}/create-product-sheet", 
		parameters : parameters_7 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_7_0
		| response_7_1
		| response_7_2
		| response_7_3
		| response_7_4
	>

	get(
		path: "/entry/organization-panel/{organizationId}*", 
		parameters : parameters_8 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_8_0
		| response_8_1
		| response_8_2
	>

	get(
		path: "/entry/login" | "/entry/register", 
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_9_0
	>

	get(
		path: "/entry/edit-profile" | "/entry/my-organizations", 
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_10_0
		| response_10_1
	>

	get(
		path: "/entry*", 
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_11_0
	>

	get(
		path: "/navigation-bar", 
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_12_0
	>

	post(
		path: "/register", 
		body: request_body_13,
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_13_0
		| response_13_1
		| response_13_2
		| response_13_3
		| response_13_4
	>

	post(
		path: "/login", 
		body: request_body_14,
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_14_0
		| response_14_1
		| response_14_2
	>

	patch(
		path: "/organization/{organizationId}/user/{userId}", 
		body: request_body_15,
		parameters : parameters_15 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_15_0
		| response_15_1
		| response_15_2
		| response_15_3
		| response_15_4
		| response_15_5
	>

	delete(
		path: "/organization/{organizationId}/user/{userId}", 
		parameters : parameters_16 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_16_0
		| response_16_1
		| response_16_2
		| response_16_3
		| response_16_4
		| response_16_5
	>

	get(
		path: "/user", 
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_17_0
		| response_17_1
		| response_17_2
	>

	patch(
		path: "/user", 
		body: request_body_18,
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_18_0
		| response_18_1
		| response_18_2
	>

	delete(
		path: "/image-product-sheet/{imageProductSheetId}", 
		parameters : parameters_19 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_19_0
		| response_19_1
		| response_19_2
		| response_19_3
		| response_19_4
	>

	get(
		path: "/organization/{organizationId}/user", 
		parameters : parameters_20 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_20_0
		| response_20_1
		| response_20_2
	>

	post(
		path: "/organization/{organizationId}/user", 
		body: request_body_21,
		parameters : parameters_21 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_21_0
		| response_21_1
		| response_21_2
		| response_21_3
		| response_21_4
		| response_21_5
		| response_21_6
	>

	get(
		path: "/user/organizations", 
		parameters ?: parameters_22 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_22_0
		| response_22_1
		| response_22_2
	>

	delete(
		path: "/product-sheet/{productSheetId}/category/{categoryName}", 
		parameters : parameters_23 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_23_0
		| response_23_1
		| response_23_2
		| response_23_3
		| response_23_4
		| response_23_5
	>

	get(
		path: "/product-sheet/{productSheetId}", 
		parameters : parameters_24 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_24_0
		| response_24_1
		| response_24_2
		| response_24_3
		| response_24_4
	>

	patch(
		path: "/product-sheet/{productSheetId}", 
		body: request_body_25,
		parameters : parameters_25 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_25_0
		| response_25_1
		| response_25_2
		| response_25_3
		| response_25_4
	>

	get(
		path: "/product-sheet/{productSheetId}/categories", 
		parameters : parameters_26 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_26_0
		| response_26_1
		| response_26_2
		| response_26_3
		| response_26_4
	>

	post(
		path: "/product-sheet/{productSheetId}/facet", 
		body: request_body_27,
		parameters : parameters_27 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_27_0
		| response_27_1
		| response_27_2
		| response_27_3
		| response_27_4
		| response_27_5
	>

	post(
		path: "/product-sheet/{productSheetId}/category", 
		body: request_body_28,
		parameters : parameters_28 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_28_0
		| response_28_1
		| response_28_2
		| response_28_3
		| response_28_4
		| response_28_5
		| response_28_6
	>

	get(
		path: "/product-sheet/{productSheetId}/facets", 
		parameters : parameters_29 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_29_0
		| response_29_1
		| response_29_2
		| response_29_3
		| response_29_4
	>

	patch(
		path: "/product-sheet/{productSheetId}/facet/{facetType}", 
		body: request_body_30,
		parameters : parameters_30 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_30_0
		| response_30_1
		| response_30_2
		| response_30_3
		| response_30_4
		| response_30_5
	>

	delete(
		path: "/product-sheet/{productSheetId}/facet/{facetType}", 
		parameters : parameters_31 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_31_0
		| response_31_1
		| response_31_2
		| response_31_3
		| response_31_4
		| response_31_5
	>

	get(
		path: "/product-sheet/{productSheetId}/images", 
		parameters : parameters_32 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_32_0
		| response_32_1
		| response_32_2
		| response_32_3
		| response_32_4
	>

	post(
		path: "/product-sheet/{productSheetId}/image", 
		body: unknown,
		parameters : parameters_33 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_33_0
		| response_33_1
		| response_33_2
		| response_33_3
		| response_33_4
		| response_33_5
		| response_33_6
	>

	patch(
		path: "/product/{sku}", 
		body: request_body_34,
		parameters : parameters_34 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_34_0
		| response_34_1
		| response_34_2
		| response_34_3
		| response_34_4
	>

	post(
		path: "/organization/{organizationId}/product-sheet", 
		body: request_body_35,
		parameters : parameters_35 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_35_0
		| response_35_1
		| response_35_2
		| response_35_3
		| response_35_4
	>

	put(
		path: "/organization/{organizationId}/logo", 
		body: unknown,
		parameters : parameters_36 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_36_0
		| response_36_1
		| response_36_2
		| response_36_3
		| response_36_4
		| response_36_5
	>

	post(
		path: "/product-sheet/{productSheetId}/product", 
		body: request_body_37,
		parameters : parameters_37 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_37_0
		| response_37_1
		| response_37_2
		| response_37_3
		| response_37_4
		| response_37_5
		| response_37_6
	>

	get(
		path: "/organization/{organizationId}/product-sheets", 
		parameters : parameters_38 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_38_0
		| response_38_1
		| response_38_2
		| response_38_3
		| response_38_4
	>

	get(
		path: "/organization/{organizationId}", 
		parameters : parameters_39 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_39_0
		| response_39_1
		| response_39_2
		| response_39_3
		| response_39_4
	>

	patch(
		path: "/organization/{organizationId}", 
		body: request_body_40,
		parameters : parameters_40 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_40_0
		| response_40_1
		| response_40_2
		| response_40_3
		| response_40_4
	>

	get(
		path: "/organization/{organizationId}/warehouses", 
		parameters : parameters_41 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_41_0
		| response_41_1
		| response_41_2
		| response_41_3
		| response_41_4
	>

	get(
		path: "/organization/{organizationId}/users", 
		parameters : parameters_42 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_42_0
		| response_42_1
		| response_42_2
		| response_42_3
		| response_42_4
	>

	get(
		path: "/organization/{organizationId}/products", 
		parameters : parameters_43 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_43_0
		| response_43_1
		| response_43_2
		| response_43_3
		| response_43_4
	>

	post(
		path: "/organization/{organizationId}/warehouse", 
		body: request_body_44,
		parameters : parameters_44 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_44_0
		| response_44_1
		| response_44_2
		| response_44_3
		| response_44_4
		| response_44_5
	>

	post(
		path: "/category", 
		body: request_body_45,
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_45_0
		| response_45_1
		| response_45_2
		| response_45_3
	>

	post(
		path: "/organization", 
		body: request_body_46,
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_46_0
		| response_46_1
		| response_46_2
		| response_46_3
		| response_46_4
		| response_46_5
	>

	put(
		path: "/category/{categoryName}/image", 
		body: unknown,
		parameters : parameters_47 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_47_0
		| response_47_1
		| response_47_2
		| response_47_3
		| response_47_4
	>

	patch(
		path: "/organization/{organizationId}@admin", 
		body: request_body_48,
		parameters : parameters_48 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_48_0
		| response_48_1
		| response_48_2
		| response_48_3
	>

	patch(
		path: "/category/{categoryName}", 
		body: request_body_49,
		parameters : parameters_49 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_49_0
		| response_49_1
		| response_49_2
		| response_49_3
		| response_49_4
	>

	post(
		path: "/navigation-item", 
		body: request_body_50,
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_50_0
		| response_50_1
		| response_50_2
		| response_50_3
	>

	get(
		path: "/navigation-items", 
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_51_0
		| response_51_1
		| response_51_2
	>

	patch(
		path: "/navigation-item/{navigationItemId}", 
		body: request_body_52,
		parameters : parameters_52 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_52_0
		| response_52_1
		| response_52_2
		| response_52_3
		| response_52_4
		| response_52_5
	>

	delete(
		path: "/navigation-item/{navigationItemId}", 
		parameters : parameters_53 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_53_0
		| response_53_1
		| response_53_2
		| response_53_3
	>

	get(
		path: "/parent-category/{parentCategoryName}/categories", 
		parameters : parameters_54 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_54_0
		| response_54_1
		| response_54_2
		| response_54_3
	>

	post(
		path: "/parent-category/{parentCategoryName}/category", 
		body: request_body_55,
		parameters : parameters_55 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_55_0
		| response_55_1
		| response_55_2
		| response_55_3
		| response_55_4
		| response_55_5
	>

	get(
		path: "/organizations", 
		parameters ?: parameters_56 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_56_0
		| response_56_1
		| response_56_2
	>

	patch(
		path: "/parent-category/{parentCategoryName}", 
		body: request_body_57,
		parameters : parameters_57 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_57_0
		| response_57_1
		| response_57_2
		| response_57_3
		| response_57_4
	>

	post(
		path: "/parent-category", 
		body: request_body_58,
		parameters ?: UndefinedRequestParameters & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_58_0
		| response_58_1
		| response_58_2
		| response_58_3
	>

	get(
		path: "/users", 
		parameters ?: parameters_59 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_59_0
		| response_59_1
		| response_59_2
	>

	patch(
		path: "/user/{userId}@admin", 
		body: request_body_60,
		parameters : parameters_60 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_60_0
		| response_60_1
		| response_60_2
		| response_60_3
		| response_60_4
	>

	delete(
		path: "/parent-category/{parentCategoryName}/category/{categoryName}", 
		parameters : parameters_61 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_61_0
		| response_61_1
		| response_61_2
		| response_61_3
	>

	patch(
		path: "/warehouse/{warehouseId}", 
		body: request_body_62,
		parameters : parameters_62 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_62_0
		| response_62_1
		| response_62_2
		| response_62_3
		| response_62_4
		| response_62_5
	>

	get(
		path: "/parent-categories", 
		parameters ?: parameters_63 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_63_0
		| response_63_1
		| response_63_2
	>

	get(
		path: "/full-product-sheet/{id}", 
		parameters : parameters_64 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_64_0
		| response_64_1
	>

	get(
		path: "/full-product-sheets", 
		parameters ?: parameters_65 & BaseRequestParameters,
		interceptorParams?: interceptorParameter
	): EnrichedRequestor<
		response_65_0
	>

}

/** @deprecated */
export type EnrichedDuplojsTo<
	interceptorParameter extends {} = {},
> = EnrichedDuploTo<interceptorParameter>;
